-- Script for Milliman Plan Recommendations -> Step 4a
-- Rohan

-- dpc to co-op assistance


-- duals cc pts
select distinct prp.patient_id, prp."primary", prp.referring_partner_id, rp.name
into raw.plan_compare_covenant_care_duals
from fdw_member_doc.patient_referring_partners prp
         join fdw_member_doc.referring_partners rp on rp.id = prp.referring_partner_id
where patient_id in
      (select distinct cc.patient_id
       from raw.plan_compare_patients_covenant_care cc
       where patient_id in
             (select distinct memberid::bigint from junk.pc_mm_all_covenant_care_plan_recommendations))
  and prp.primary;

  -- 4a with CC Duals  edits
DROP TABLE IF EXISTS _dual_mapping;

CREATE TEMP TABLE _dual_mapping AS

SELECT *
FROM (VALUES ('NA', 'Non-Medicaid'),
             ('0', 'Not Medicare Enrolled'),
             ('01', 'QMB Only'),
             ('02', 'QMB +'),
             ('03', 'SLMB Only'),
             ('04', 'SLMB +'),
             ('05', 'QDWI'),
             ('06', 'QI'),
             ('08', 'Other Dual with Medicaid'),
             ('09', 'Other Dual without Medicaid'),
             ('99', 'Unknown')) x(dual_level, dual_type);


DROP TABLE IF EXISTS _lis_mapping;

CREATE TEMP TABLE _lis_mapping AS

SELECT *
FROM (VALUES ('0', 'No Extra Help'),
             ('01', 'Level 3 - 100% ($0/$0)'),
             ('02', 'Level 2 - 100% ($1.45/$4.30)'),
             ('03', 'Level 1 - 100% ($4.15/$10.35)'),
             ('04', 'Level 1 - 100% ($4.15/$10.35)'),
             ('05', 'Level 4 - 100% (15% Rx coinsurance)'),
             ('06', 'Level 4 - 75% (15% Rx coinsurance)'),
             ('07', 'Level 4 - 50% (15% Rx coinsurance)'),
             ('08', 'Level 4 - 25% (15% Rx coinsurance)'),
             ('09', 'No Extra Help'),
             ('10', 'No Extra Help'),
             ('13', 'No Extra Help')) x(lis_level, lis_type);


-- med supp premiums by plan
DROP TABLE IF EXISTS _avg_med_supp_premiums_by_plan;
CREATE TEMP TABLE _avg_med_supp_premiums_by_plan AS

SELECT *
FROM (VALUES ('A', 'Medicare Supplement', '188.30'),
             ('B', 'Medicare Supplement', '197.07'),
             ('C', 'Medicare Supplement', '211.15'),
             ('D', 'Medicare Supplement', '198.56'),
             ('F', 'Medicare Supplement', '206.69'),
             ('FH', 'Medicare Supplement', '123.91'),
             ('G', 'Medicare Supplement', '183.38'),
             ('GH', 'Medicare Supplement', '111.68'),
             ('K', 'Medicare Supplement', '146.93'),
             ('L', 'Medicare Supplement', '187.54'),
             ('M', 'Medicare Supplement', '173.16'),
             ('N', 'Medicare Supplement', '162.89'),
             ('Not Specified', 'Medicare Supplement',
              '$184.58')) x(med_supp_plan_type, med_supp_plan_name, med_supp_monthly_premium);


-- mm med supp mapping
DROP TABLE IF EXISTS _milliman_med_supp_plans;
CREATE TEMP TABLE _milliman_med_supp_plans AS


SELECT *
FROM (VALUES ('A', 'ACCENDO INS CO (PREFERRED)	', '46663'),
             ('A', 'ACCENDO INS CO (STANDARD)	', '46430'),
             ('A', 'ACE PROPERTY & CASUALTY INS CO (PREFERRED)	', '53665'),
             ('A', 'ACE PROPERTY & CASUALTY INS CO (STANDARD)	', '53669'),
             ('A', 'AETNA HEALTH & LIFE INS CO (PREFERRED)	', '44239'),
             ('A', 'AETNA HEALTH & LIFE INS CO (STANDARD)	', '44290'),
             ('A', 'AETNA LIFE INS CO	', '42914'),
             ('A', 'AMERICAN BENEFIT LIFE INS CO (PREFERRED)	', '42516'),
             ('A', 'AMERICAN BENEFIT LIFE INS CO (STANDARD)	', '42438'),
             ('A', 'AMERICAN CONTINENTAL INS CO (PREFERRED)	', '43109'),
             ('A', 'AMERICAN CONTINENTAL INS CO (STANDARD)	', '43088'),
             ('A', 'AMERICAN HOME LIFE INS CO (PREFERRED)	', '53592'),
             ('A', 'AMERICAN HOME LIFE INS CO (STANDARD)	', '53480'),
             ('A', 'AMERICAN REPUBLIC CORP INS CO	', '43256'),
             ('A', 'AMERICAN REPUBLIC CORP INS CO (PREFERRED)	', '43260'),
             ('A', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO	', '44897'),
             ('A', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO	', '45768'),
             ('A', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO (TOBACCO)	', '44901'),
             ('A', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO (TOBACCO)	', '45772'),
             ('A', 'ASSURED LIFE ASSN	', '43215'),
             ('A', 'ASSURED LIFE ASSN (TOBACCO)	', '43221'),
             ('A', 'ATLANTIC COAST LIFE INS CO	', '45730'),
             ('A', 'ATLANTIC COAST LIFE INS CO (TOBACCO)	', '45734'),
             ('A', 'BANKERS FIDELITY ASSURANCE CO (PREFERRED)	', '43927'),
             ('A', 'BANKERS FIDELITY ASSURANCE CO (STANDARD)	', '44462'),
             ('A', 'BANKERS FIDELITY LIFE INS CO (PREFERRED)	', '43637'),
             ('A', 'BANKERS FIDELITY LIFE INS CO (STANDARD)	', '43712'),
             ('A', 'BANKERS RESERVE LIFE INS CO OF WISCONSIN	', '53738'),
             ('A', 'BANKERS RESERVE LIFE INS CO OF WISCONSIN (TOBACCO)	', '53771'),
             ('A', 'BLUECROSS BLUESHIELD OF TENNESSEE	', '43481'),
             ('A', 'BLUECROSS BLUESHIELD OF TENNESSEE (TOBACCO)	', '43484'),
             ('A', 'CAPITOL LIFE INS CO (PREFERRED)	', '46266'),
             ('A', 'CAPITOL LIFE INS CO (STANDARD)	', '46270'),
             ('A', 'CENTRAL STATES HEALTH & LIFE OF OMAHA (PREFERRED)	', '45456'),
             ('A', 'CENTRAL STATES HEALTH & LIFE OF OMAHA (STANDARD)	', '45460'),
             ('A', 'CIGNA HEALTH & LIFE INS CO (PREFERRED)	', '44643'),
             ('A', 'CIGNA HEALTH & LIFE INS CO (STANDARD)	', '44726'),
             ('A', 'CIGNA NATIONAL HEALTH INS CO (PREFERRED)	', '46053'),
             ('A', 'CIGNA NATIONAL HEALTH INS CO (STANDARD II)	', '42106'),
             ('A', 'CIGNA NATIONAL HEALTH INS CO (STANDARD III)	', '42110'),
             ('A', 'CIGNA NATIONAL HEALTH INS CO (STANDARD)	', '46057'),
             ('A', 'COLONIAL PENN LIFE INS CO (PREFERRED)	', '44260'),
             ('A', 'COLONIAL PENN LIFE INS CO (STANDARD)	', '43777'),
             ('A', 'COLONIAL PENN LIFE INS CO (SUBSTANDARD)	', '44215'),
             ('A', 'COMPBENEFITS INS CO (PREFERRED)	', '46395'),
             ('A', 'COMPBENEFITS INS CO (STANDARD)	', '46400'),
             ('A', 'CONTINENTAL LIFE INS OF BRENTWOOD (PREFERRED)	', '42943'),
             ('A', 'CONTINENTAL LIFE INS OF BRENTWOOD (STANDARD)	', '42948'),
             ('A', 'ELIPS LIFE INS CO (PREFERRED)	', '42244'),
             ('A', 'ELIPS LIFE INS CO (STANDARD)	', '42249'),
             ('A', 'EPIC LIFE INS CO	', '44715'),
             ('A', 'ERIE FAMILY LIFE INS CO	', '46594'),
             ('A', 'ERIE FAMILY LIFE INS CO (TOBACCO)	', '46598'),
             ('A', 'FEDERAL LIFE INS CO	', '46561'),
             ('A', 'FEDERAL LIFE INS CO (TOBACCO)	', '46565'),
             ('A', 'FIRST HEALTH LIFE & HEALTH INS CO (PREFERRED)	', '45079'),
             ('A', 'FIRST HEALTH LIFE & HEALTH INS CO (STANDARD)	', '44991'),
             ('A', 'GLOBE LIFE & ACCIDENT INS CO	', '42983'),
             ('A', 'GLOBE LIFE & ACCIDENT INS CO	', '46046'),
             ('A', 'GLOBE LIFE & ACCIDENT INS CO (PREFERRED)	', '46211'),
             ('A', 'GREAT SOUTHERN LIFE INS CO	', '45738'),
             ('A', 'GREAT SOUTHERN LIFE INS CO (DIRECT TOBACCO)	', '46152'),
             ('A', 'GREAT SOUTHERN LIFE INS CO (DIRECT)	', '46288'),
             ('A', 'GREAT SOUTHERN LIFE INS CO (TOBACCO)	', '45636'),
             ('A', 'GUARANTEE TRUST LIFE INS CO (PREFERRED)	', '43848'),
             ('A', 'GUARANTEE TRUST LIFE INS CO (STANDARD)	', '43799'),
             ('A', 'HUMANA INS CO (HEALTHY LIVING PREFERRED)	', '45282'),
             ('A', 'HUMANA INS CO (HEALTHY LIVING STANDARD)	', '45277'),
             ('A', 'HUMANA INS CO (PREFERRED)	', '42958'),
             ('A', 'HUMANA INS CO (STANDARD)	', '42953'),
             ('A', 'HUMANADENTAL INS CO (PREFERRED)	', '44444'),
             ('A', 'HUMANADENTAL INS CO (STANDARD)	', '44438'),
             ('A', 'INDEPENDENCE AMERICAN INS CO	', '42026'),
             ('A', 'INDEPENDENCE AMERICAN INS CO (TOBACCO)	', '42030'),
             ('A', 'LUMICO LIFE INS CO (PREFERRED)	', '45704'),
             ('A', 'LUMICO LIFE INS CO (STANDARD)	', '45708'),
             ('A', 'MANHATTAN LIFE INS CO (PREFERRED)	', '43866'),
             ('A', 'MANHATTAN LIFE INS CO (STANDARD)	', '43874'),
             ('A', 'MANHATTANLIFE INS & ANNUITY CO (PREFERRED)	', '42018'),
             ('A', 'MANHATTANLIFE INS & ANNUITY CO (STANDARD)	', '42022'),
             ('A', 'MEDICO CORP LIFE INS CO	', '44249'),
             ('A', 'MEDICO CORP LIFE INS CO (PREFERRED)	', '44254'),
             ('A', 'MEDICO INS CO (PREFERRED)	', '42178'),
             ('A', 'MEDICO INS CO (PREFERRED)	', '43068'),
             ('A', 'MEDICO INS CO (STANDARD I)	', '42184'),
             ('A', 'MEDICO INS CO (STANDARD II)	', '42070'),
             ('A', 'MEDICO INS CO (STANDARD)	', '43108'),
             ('A', 'MUTUAL OF OMAHA INS CO	', '43513'),
             ('A', 'MUTUAL OF OMAHA INS CO (TOBACCO)	', '43177'),
             ('A', 'NASSAU LIFE INS CO OF KANSAS (PREFERRED)	', '46358'),
             ('A', 'NASSAU LIFE INS CO OF KANSAS (STANDARD)	', '46362'),
             ('A', 'NATIONAL GUARDIAN LIFE INS CO	', '45304'),
             ('A', 'NATIONAL GUARDIAN LIFE INS CO (TOBACCO)	', '45308'),
             ('A', 'NATIONAL HEALTH INS CO (PREFERRED II)	', '42631'),
             ('A', 'NATIONAL HEALTH INS CO (PREFERRED)	', '42636'),
             ('A', 'NATIONAL HEALTH INS CO (PREFERRED)	', '45927'),
             ('A', 'NATIONAL HEALTH INS CO (STANDARD)	', '42623'),
             ('A', 'NATIONAL HEALTH INS CO (STANDARD)	', '45932'),
             ('A', 'NEW ERA LIFE INS CO	', '42688'),
             ('A', 'NEW ERA LIFE INS CO (TOBACCO)	', '42747'),
             ('A', 'NEW ERA LIFE INS CO OF THE MIDWEST	', '42393'),
             ('A', 'NEW ERA LIFE INS CO OF THE MIDWEST	', '42759'),
             ('A', 'NEW ERA LIFE INS CO OF THE MIDWEST (TOBACCO)	', '42399'),
             ('A', 'NEW ERA LIFE INS CO OF THE MIDWEST (TOBACCO)	', '42754'),
             ('A', 'OMAHA INS CO	', '44266'),
             ('A', 'OMAHA INS CO (TOBACCO)	', '44269'),
             ('A', 'ORDER OF UNITED COMMERCIAL TRAVELERS	', '45238'),
             ('A', 'ORDER OF UNITED COMMERCIAL TRAVELERS (TOBACCO)	', '45966'),
             ('A', 'OXFORD LIFE INS CO	', '43833'),
             ('A', 'OXFORD LIFE INS CO (TOBACCO)	', '43837'),
             ('A', 'PAN-AMERICAN LIFE INS CO	', '45179'),
             ('A', 'PAN-AMERICAN LIFE INS CO (TOBACCO)	', '45919'),
             ('A', 'PEKIN LIFE INS CO	', '42704'),
             ('A', 'PEKIN LIFE INS CO (TOBACCO)	', '43899'),
             ('A', 'PHILADELPHIA AMERICAN LIFE INS	', '43375'),
             ('A', 'PHILADELPHIA AMERICAN LIFE INS (TOBACCO)	', '43379'),
             ('A', 'PHYSICIANS LIFE INS CO	', '46258'),
             ('A', 'PHYSICIANS LIFE INS CO (TOBACCO)	', '46123'),
             ('A', 'PURITAN LIFE INS CO OF AMERICA (PREFERRED)	', '44859'),
             ('A', 'PURITAN LIFE INS CO OF AMERICA (STANDARD)	', '44863'),
             ('A', 'RESERVE NATIONAL INS CO (PREFERRED)	', '43785'),
             ('A', 'RESERVE NATIONAL INS CO (STANDARD TOBACCO)	', '42718'),
             ('A', 'RESERVE NATIONAL INS CO (STANDARD)	', '42659'),
             ('A', 'RESOURCE LIFE INS CO	', '46008'),
             ('A', 'S. USA LIFE INS CO (PREFERRED)	', '44498'),
             ('A', 'S. USA LIFE INS CO (STANDARD)	', '44496'),
             ('A', 'SBLI USA LIFE INS CO (PREFERRED)	', '42336'),
             ('A', 'SBLI USA LIFE INS CO (STANDARD TOBACCO)	', '42276'),
             ('A', 'SBLI USA LIFE INS CO (STANDARD)	', '42272'),
             ('A', 'SHENANDOAH LIFE INS CO	', '44021'),
             ('A', 'SHENANDOAH LIFE INS CO (TOBACCO)	', '44025'),
             ('A', 'SILVERSCRIPT INS CO (PREFERRED)	', '46682'),
             ('A', 'SILVERSCRIPT INS CO (STANDARD)	', '46687'),
             ('A', 'SOUTHERN GUARANTY INS CO	', '46614'),
             ('A', 'SOUTHERN GUARANTY INS CO (TOBACCO)	', '46490'),
             ('A', 'STANDARD LIFE & CASUALTY INS CO	', '44001'),
             ('A', 'STANDARD LIFE & CASUALTY INS CO	', '46215'),
             ('A', 'STANDARD LIFE & CASUALTY INS CO (TOBACCO)	', '44005'),
             ('A', 'STANDARD LIFE & CASUALTY INS CO (TOBACCO)	', '46219'),
             ('A', 'STATE FARM MUTUAL AUTOMOBILE INS CO	', '42862'),
             ('A', 'STATE FARM MUTUAL AUTOMOBILE INS CO (TOBACCO)	', '44811'),
             ('A', 'STATE MUTUAL INS CO (BROKERAGE PREFERRED)	', '44472'),
             ('A', 'STATE MUTUAL INS CO (BROKERAGE STANDARD)	', '44532'),
             ('A', 'STATE MUTUAL INS CO (BRONZE)	', '42046'),
             ('A', 'STATE MUTUAL INS CO (DIRECT PREFERRED)	', '42876'),
             ('A', 'STATE MUTUAL INS CO (DIRECT STANDARD)	', '42683'),
             ('A', 'STATE MUTUAL INS CO (GOLD)	', '42146'),
             ('A', 'STATE MUTUAL INS CO (SILVER)	', '42037'),
             ('A', 'TIER ONE INS CO (PREFERRED)	', '53486'),
             ('A', 'TIER ONE INS CO (STANDARD)	', '53702'),
             ('A', 'TRANSAMERICA LIFE INS CO	', '44090'),
             ('A', 'TRANSAMERICA LIFE INS CO (TOBACCO)	', '43991'),
             ('A', 'TRH HEALTH INS CO	', '42475'),
             ('A', 'TRH HEALTH INS CO (TOBACCO)	', '42479'),
             ('A', 'UNIFIED LIFE INS CO (PREFERRED)	', '45090'),
             ('A', 'UNIFIED LIFE INS CO (STANDARD)	', '45024'),
             ('A', 'UNION SECURITY INS CO (PREFERRED)	', '45806'),
             ('A', 'UNION SECURITY INS CO (STANDARD)	', '45698'),
             ('A', 'UNITED AMERICAN INS CO (PREFERRED)	', '43448'),
             ('A', 'UNITED AMERICAN INS CO (STANDARD)	', '43440'),
             ('A', 'UNITED INSURANCE COMPANY OF AMERICA (PREFERRED)	', '42056'),
             ('A', 'UNITED INSURANCE COMPANY OF AMERICA (STANDARD)	', '42062'),
             ('A', 'UNITED NATIONAL LIFE INS CO OF AMERICA (PREFERRED)	', '43580'),
             ('A', 'UNITED NATIONAL LIFE INS CO OF AMERICA (STANDARD)	', '43584'),
             ('A', 'UNITED OF OMAHA	', '43520'),
             ('A', 'UNITED OF OMAHA (TOBACCO)	', '43473'),
             ('A', 'UNITED STATES FIRE INS CO (PREFERRED)	', '46324'),
             ('A', 'UNITED STATES FIRE INS CO (STANDARD)	', '46332'),
             ('A', 'UNITED WORLD LIFE INS CO	', '43384'),
             ('A', 'UNITED WORLD LIFE INS CO (TOBACCO)	', '43392'),
             ('A', 'UNITEDHEALTHCARE	', '44669'),
             ('A', 'UNITEDHEALTHCARE (DISCOUNT)	', '44755'),
             ('A', 'UNITEDHEALTHCARE (LEVEL 1)	', '44591'),
             ('A', 'UNITEDHEALTHCARE (LEVEL 2)	', '44599'),
             ('A', 'UNITEDHEALTHCARE (LEVEL 2)	', '44677'),
             ('A', 'UNITEDHEALTHCARE (TOBACCO DISCOUNT)	', '44513'),
             ('A', 'UNITEDHEALTHCARE (TOBACCO LEVEL 1)	', '45118'),
             ('A', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '44969'),
             ('A', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '45110'),
             ('A', 'UNITEDHEALTHCARE (TOBACCO)	', '44521'),
             ('A', 'USAA LIFE INSURANCE COMPANY	', '42767'),
             ('A', 'USAA LIFE INSURANCE COMPANY (TOBACCO)	', '42870'),
             ('A', 'WASHINGTON NATIONAL INS CO (PREFERRED)	', '53625'),
             ('A', 'WASHINGTON NATIONAL INS CO (STANDARD)	', '53541'),
             ('A', 'WASHINGTON NATIONAL INS CO (SUBSTANDARD)	', '53585'),
             ('A', 'WESTERN UNITED LIFE ASR CO (PREFERRED)	', '44732'),
             ('A', 'WESTERN UNITED LIFE ASR CO (STANDARD)	', '44728'),
             ('B', 'AETNA HEALTH & LIFE INS CO (PREFERRED)	', '44240'),
             ('B', 'AETNA HEALTH & LIFE INS CO (STANDARD)	', '44291'),
             ('B', 'AETNA LIFE INS CO	', '42915'),
             ('B', 'AMERICAN CONTINENTAL INS CO (PREFERRED)	', '43110'),
             ('B', 'AMERICAN CONTINENTAL INS CO (STANDARD)	', '43089'),
             ('B', 'ASSURED LIFE ASSN	', '43216'),
             ('B', 'ASSURED LIFE ASSN (TOBACCO)	', '43222'),
             ('B', 'COLONIAL PENN LIFE INS CO (PREFERRED)	', '44261'),
             ('B', 'COLONIAL PENN LIFE INS CO (STANDARD)	', '43778'),
             ('B', 'COLONIAL PENN LIFE INS CO (SUBSTANDARD)	', '44216'),
             ('B', 'CONTINENTAL LIFE INS OF BRENTWOOD (PREFERRED)	', '42944'),
             ('B', 'CONTINENTAL LIFE INS OF BRENTWOOD (STANDARD)	', '42919'),
             ('B', 'FIRST HEALTH LIFE & HEALTH INS CO (PREFERRED)	', '45080'),
             ('B', 'FIRST HEALTH LIFE & HEALTH INS CO (STANDARD)	', '44992'),
             ('B', 'GLOBE LIFE & ACCIDENT INS CO	', '42984'),
             ('B', 'HUMANA INS CO (PREFERRED)	', '42959'),
             ('B', 'HUMANA INS CO (STANDARD)	', '42954'),
             ('B', 'NEW ERA LIFE INS CO OF THE MIDWEST	', '42760'),
             ('B', 'NEW ERA LIFE INS CO OF THE MIDWEST (TOBACCO)	', '42755'),
             ('B', 'ORDER OF UNITED COMMERCIAL TRAVELERS	', '45239'),
             ('B', 'ORDER OF UNITED COMMERCIAL TRAVELERS (TOBACCO)	', '45967'),
             ('B', 'RESERVE NATIONAL INS CO (STANDARD TOBACCO)	', '42719'),
             ('B', 'RESERVE NATIONAL INS CO (STANDARD)	', '42660'),
             ('B', 'SILVERSCRIPT INS CO (PREFERRED)	', '46683'),
             ('B', 'SILVERSCRIPT INS CO (STANDARD)	', '46688'),
             ('B', 'STATE MUTUAL INS CO (BROKERAGE PREFERRED)	', '44473'),
             ('B', 'STATE MUTUAL INS CO (BROKERAGE STANDARD)	', '44464'),
             ('B', 'STATE MUTUAL INS CO (BRONZE)	', '42047'),
             ('B', 'STATE MUTUAL INS CO (DIRECT PREFERRED)	', '42877'),
             ('B', 'STATE MUTUAL INS CO (DIRECT STANDARD)	', '42684'),
             ('B', 'STATE MUTUAL INS CO (GOLD)	', '42147'),
             ('B', 'STATE MUTUAL INS CO (SELECT PREFERRED)	', '42789'),
             ('B', 'STATE MUTUAL INS CO (SELECT STANDARD)	', '42785'),
             ('B', 'STATE MUTUAL INS CO (SILVER)	', '42038'),
             ('B', 'TRANSAMERICA LIFE INS CO	', '44091'),
             ('B', 'TRANSAMERICA LIFE INS CO (TOBACCO)	', '43992'),
             ('C', 'UNITED AMERICAN INS CO (PREFERRED)	', '43368'),
             ('C', 'UNITED AMERICAN INS CO (STANDARD)	', '43441'),
             ('C', 'UNITED STATES FIRE INS CO (PREFERRED)	', '46325'),
             ('C', 'UNITED STATES FIRE INS CO (STANDARD)	', '46333'),
             ('C', 'UNITEDHEALTHCARE	', '44670'),
             ('C', 'UNITEDHEALTHCARE (DISCOUNT)	', '44756'),
             ('C', 'UNITEDHEALTHCARE (LEVEL 1)	', '44592'),
             ('C', 'UNITEDHEALTHCARE (LEVEL 2)	', '44600'),
             ('C', 'UNITEDHEALTHCARE (LEVEL 2)	', '44678'),
             ('C', 'UNITEDHEALTHCARE (TOBACCO DISCOUNT)	', '44514'),
             ('C', 'UNITEDHEALTHCARE (TOBACCO LEVEL 1)	', '45119'),
             ('C', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '44970'),
             ('C', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '45111'),
             ('C', 'UNITEDHEALTHCARE (TOBACCO)	', '44522'),
             ('C', 'AMERICAN CONTINENTAL INS CO (PREFERRED)	', '43111'),
             ('C', 'AMERICAN CONTINENTAL INS CO (STANDARD)	', '43090'),
             ('C', 'ASSURED LIFE ASSN	', '43217'),
             ('C', 'ASSURED LIFE ASSN (TOBACCO)	', '43223'),
             ('C', 'ATLANTIC COAST LIFE INS CO	', '45731'),
             ('C', 'ATLANTIC COAST LIFE INS CO (TOBACCO)	', '45735'),
             ('C', 'BLUECROSS BLUESHIELD OF TENNESSEE	', '45081'),
             ('C', 'BLUECROSS BLUESHIELD OF TENNESSEE (TOBACCO)	', '45083'),
             ('C', 'CENTRAL STATES HEALTH & LIFE OF OMAHA (PREFERRED)	', '45457'),
             ('C', 'CENTRAL STATES HEALTH & LIFE OF OMAHA (STANDARD)	', '45461'),
             ('C', 'CONTINENTAL LIFE INS OF BRENTWOOD (PREFERRED)	', '42945'),
             ('C', 'CONTINENTAL LIFE INS OF BRENTWOOD (STANDARD)	', '42920'),
             ('C', 'EPIC LIFE INS CO	', '44716'),
             ('C', 'GLOBE LIFE & ACCIDENT INS CO	', '42967'),
             ('C', 'HUMANA INS CO (PREFERRED)	', '42960'),
             ('C', 'HUMANA INS CO (STANDARD)	', '42955'),
             ('C', 'MANHATTAN LIFE INS CO (PREFERRED)	', '43868'),
             ('C', 'MANHATTAN LIFE INS CO (STANDARD)	', '43876'),
             ('C', 'NEW ERA LIFE INS CO	', '42690'),
             ('C', 'NEW ERA LIFE INS CO (TOBACCO)	', '42749'),
             ('C', 'NEW ERA LIFE INS CO OF THE MIDWEST	', '42761'),
             ('C', 'NEW ERA LIFE INS CO OF THE MIDWEST	', '53430'),
             ('C', 'NEW ERA LIFE INS CO OF THE MIDWEST (TOBACCO)	', '42756'),
             ('C', 'NEW ERA LIFE INS CO OF THE MIDWEST (TOBACCO)	', '53725'),
             ('C', 'ORDER OF UNITED COMMERCIAL TRAVELERS	', '45971'),
             ('C', 'ORDER OF UNITED COMMERCIAL TRAVELERS (TOBACCO)	', '45973'),
             ('C', 'PHILADELPHIA AMERICAN LIFE INS	', '43376'),
             ('C', 'PHILADELPHIA AMERICAN LIFE INS (TOBACCO)	', '43380'),
             ('C', 'RESERVE NATIONAL INS CO (PREFERRED)	', '43786'),
             ('C', 'RESERVE NATIONAL INS CO (STANDARD TOBACCO)	', '42720'),
             ('C', 'RESERVE NATIONAL INS CO (STANDARD)	', '42661'),
             ('C', 'STATE FARM MUTUAL AUTOMOBILE INS CO	', '42864'),
             ('C', 'STATE FARM MUTUAL AUTOMOBILE INS CO (TOBACCO)	', '44812'),
             ('C', 'STATE MUTUAL INS CO (BROKERAGE PREFERRED)	', '44474'),
             ('C', 'STATE MUTUAL INS CO (BROKERAGE STANDARD)	', '44465'),
             ('C', 'STATE MUTUAL INS CO (BRONZE)	', '42048'),
             ('C', 'STATE MUTUAL INS CO (DIRECT PREFERRED)	', '42878'),
             ('C', 'STATE MUTUAL INS CO (DIRECT STANDARD)	', '42685'),
             ('C', 'STATE MUTUAL INS CO (GOLD)	', '42148'),
             ('C', 'STATE MUTUAL INS CO (SELECT PREFERRED)	', '42790'),
             ('C', 'STATE MUTUAL INS CO (SELECT STANDARD)	', '42786'),
             ('C', 'STATE MUTUAL INS CO (SILVER)	', '42039'),
             ('C', 'TRANSAMERICA LIFE INS CO	', '44092'),
             ('C', 'TRANSAMERICA LIFE INS CO (TOBACCO)	', '43993'),
             ('C', 'UNITED AMERICAN INS CO (PREFERRED)	', '43369'),
             ('C', 'UNITED AMERICAN INS CO (STANDARD)	', '43442'),
             ('C', 'UNITEDHEALTHCARE	', '44671'),
             ('C', 'UNITEDHEALTHCARE (DISCOUNT)	', '44757'),
             ('C', 'UNITEDHEALTHCARE (LEVEL 1)	', '44593'),
             ('C', 'UNITEDHEALTHCARE (LEVEL 2)	', '44601'),
             ('C', 'UNITEDHEALTHCARE (LEVEL 2)	', '44679'),
             ('C', 'UNITEDHEALTHCARE (SELECT DISCOUNT)	', '44977'),
             ('C', 'UNITEDHEALTHCARE (SELECT LEVEL 1)	', '45578'),
             ('C', 'UNITEDHEALTHCARE (SELECT LEVEL 2)	', '44981'),
             ('C', 'UNITEDHEALTHCARE (SELECT LEVEL 2)	', '45580'),
             ('C', 'UNITEDHEALTHCARE (SELECT TOBACCO DISCOUNT)	', '45590'),
             ('C', 'UNITEDHEALTHCARE (SELECT TOBACCO LEVEL 1)	', '45584'),
             ('C', 'UNITEDHEALTHCARE (SELECT TOBACCO LEVEL 2)	', '45582'),
             ('C', 'UNITEDHEALTHCARE (SELECT TOBACCO LEVEL 2)	', '45586'),
             ('C', 'UNITEDHEALTHCARE (SELECT TOBACCO)	', '45588'),
             ('C', 'UNITEDHEALTHCARE (SELECT)	', '44979'),
             ('C', 'UNITEDHEALTHCARE (TOBACCO DISCOUNT)	', '44515'),
             ('C', 'UNITEDHEALTHCARE (TOBACCO LEVEL 1)	', '45120'),
             ('C', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '44971'),
             ('C', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '45112'),
             ('C', 'UNITEDHEALTHCARE (TOBACCO)	', '44523'),
             ('C', 'WESTERN UNITED LIFE ASR CO (PREFERRED)	', '44733'),
             ('C', 'WESTERN UNITED LIFE ASR CO (STANDARD)	', '44729'),
             ('D', 'AMERICAN CONTINENTAL INS CO (PREFERRED)	', '43112'),
             ('D', 'AMERICAN CONTINENTAL INS CO (STANDARD)	', '43091'),
             ('D', 'ASSURED LIFE ASSN	', '43218'),
             ('D', 'ASSURED LIFE ASSN (TOBACCO)	', '43224'),
             ('D', 'BLUECROSS BLUESHIELD OF TENNESSEE	', '43482'),
             ('D', 'BLUECROSS BLUESHIELD OF TENNESSEE (TOBACCO)	', '43485'),
             ('D', 'COLONIAL PENN LIFE INS CO (PREFERRED)	', '46390'),
             ('D', 'COLONIAL PENN LIFE INS CO (STANDARD)	', '46391'),
             ('D', 'COLONIAL PENN LIFE INS CO (SUBSTANDARD)	', '46392'),
             ('D', 'CONTINENTAL LIFE INS OF BRENTWOOD (PREFERRED)	', '42897'),
             ('D', 'CONTINENTAL LIFE INS OF BRENTWOOD (STANDARD)	', '42899'),
             ('D', 'NEW ERA LIFE INS CO	', '42715'),
             ('D', 'NEW ERA LIFE INS CO (TOBACCO)	', '42716'),
             ('D', 'ORDER OF UNITED COMMERCIAL TRAVELERS	', '45972'),
             ('D', 'ORDER OF UNITED COMMERCIAL TRAVELERS (TOBACCO)	', '45974'),
             ('D', 'RESERVE NATIONAL INS CO (STANDARD)	', '43009'),
             ('D', 'STATE FARM MUTUAL AUTOMOBILE INS CO	', '45826'),
             ('D', 'STATE FARM MUTUAL AUTOMOBILE INS CO (TOBACCO)	', '45829'),
             ('D', 'STATE MUTUAL INS CO (BROKERAGE PREFERRED)	', '44475'),
             ('F', 'STATE MUTUAL INS CO (BROKERAGE STANDARD)	', '44466'),
             ('F', 'STATE MUTUAL INS CO (BRONZE)	', '42049'),
             ('F', 'STATE MUTUAL INS CO (DIRECT PREFERRED)	', '42832'),
             ('F', 'STATE MUTUAL INS CO (DIRECT STANDARD)	', '42686'),
             ('F', 'STATE MUTUAL INS CO (GOLD)	', '42149'),
             ('F', 'STATE MUTUAL INS CO (SELECT PREFERRED)	', '42791'),
             ('F', 'STATE MUTUAL INS CO (SELECT STANDARD)	', '42787'),
             ('F', 'STATE MUTUAL INS CO (SILVER)	', '42040'),
             ('F', 'TRANSAMERICA LIFE INS CO	', '44093'),
             ('F', 'TRANSAMERICA LIFE INS CO (TOBACCO)	', '43994'),
             ('F', 'TRH HEALTH INS CO	', '42476'),
             ('F', 'TRH HEALTH INS CO (TOBACCO)	', '42480'),
             ('F', 'UNITED AMERICAN INS CO (PREFERRED)	', '43370'),
             ('F', 'UNITED AMERICAN INS CO (STANDARD)	', '43443'),
             ('F', 'UNITED INSURANCE COMPANY OF AMERICA (PREFERRED)	', '42057'),
             ('F', 'UNITED INSURANCE COMPANY OF AMERICA (STANDARD)	', '42063'),
             ('F', 'UNITED NATIONAL LIFE INS CO OF AMERICA (PREFERRED)	', '43581'),
             ('F', 'UNITED NATIONAL LIFE INS CO OF AMERICA (STANDARD)	', '43585'),
             ('F', 'USAA LIFE INSURANCE COMPANY	', '42768'),
             ('F', 'USAA LIFE INSURANCE COMPANY (TOBACCO)	', '42871'),
             ('F', 'ACCENDO INS CO (PREFERRED)	', '46427'),
             ('F', 'ACCENDO INS CO (STANDARD)	', '46431'),
             ('F', 'ACE PROPERTY & CASUALTY INS CO (PREFERRED)	', '53615'),
             ('F', 'ACE PROPERTY & CASUALTY INS CO (STANDARD)	', '53572'),
             ('F', 'AETNA HEALTH & LIFE INS CO (PREFERRED)	', '44241'),
             ('F', 'AETNA HEALTH & LIFE INS CO (STANDARD)	', '44292'),
             ('F', 'AETNA LIFE INS CO	', '42916'),
             ('F', 'AMERICAN BENEFIT LIFE INS CO (PREFERRED)	', '42517'),
             ('F', 'AMERICAN BENEFIT LIFE INS CO (STANDARD)	', '42439'),
             ('F', 'AMERICAN CONTINENTAL INS CO (PREFERRED)	', '43086'),
             ('F', 'AMERICAN CONTINENTAL INS CO (STANDARD)	', '43093'),
             ('F', 'AMERICAN HOME LIFE INS CO (PREFERRED)	', '53429'),
             ('F', 'AMERICAN HOME LIFE INS CO (STANDARD)	', '53491'),
             ('F', 'AMERICAN REPUBLIC CORP INS CO	', '43257'),
             ('F', 'AMERICAN REPUBLIC CORP INS CO (PREFERRED)	', '43261'),
             ('F', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO	', '44898'),
             ('F', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO	', '45769'),
             ('F', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO (TOBACCO)	', '44902'),
             ('F', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO (TOBACCO)	', '45773'),
             ('F', 'ASSURED LIFE ASSN	', '43219'),
             ('F', 'ASSURED LIFE ASSN (TOBACCO)	', '43225'),
             ('F', 'ATLANTIC COAST LIFE INS CO	', '42354'),
             ('F', 'ATLANTIC COAST LIFE INS CO (TOBACCO)	', '42355'),
             ('F', 'BANKERS FIDELITY ASSURANCE CO (PREFERRED)	', '43928'),
             ('F', 'BANKERS FIDELITY ASSURANCE CO (STANDARD)	', '44463'),
             ('F', 'BANKERS FIDELITY LIFE INS CO (PREFERRED)	', '43638'),
             ('F', 'BANKERS FIDELITY LIFE INS CO (STANDARD)	', '43713'),
             ('F', 'BANKERS RESERVE LIFE INS CO OF WISCONSIN	', '53767'),
             ('F', 'BANKERS RESERVE LIFE INS CO OF WISCONSIN (TOBACCO)	', '53750'),
             ('F', 'BLUECROSS BLUESHIELD OF TENNESSEE	', '43483'),
             ('F', 'BLUECROSS BLUESHIELD OF TENNESSEE (TOBACCO)	', '43486'),
             ('F', 'CAPITOL LIFE INS CO (PREFERRED)	', '46267'),
             ('F', 'CAPITOL LIFE INS CO (STANDARD)	', '46271'),
             ('F', 'CENTRAL STATES HEALTH & LIFE OF OMAHA (PREFERRED)	', '46388'),
             ('F', 'CENTRAL STATES HEALTH & LIFE OF OMAHA (STANDARD)	', '46389'),
             ('F', 'CIGNA HEALTH & LIFE INS CO (PREFERRED)	', '44644'),
             ('F', 'CIGNA HEALTH & LIFE INS CO (STANDARD)	', '44727'),
             ('F', 'CIGNA NATIONAL HEALTH INS CO (PREFERRED)	', '46054'),
             ('F', 'CIGNA NATIONAL HEALTH INS CO (STANDARD II)	', '42107'),
             ('F', 'CIGNA NATIONAL HEALTH INS CO (STANDARD III)	', '42111'),
             ('F', 'CIGNA NATIONAL HEALTH INS CO (STANDARD)	', '42103'),
             ('F', 'COLONIAL PENN LIFE INS CO (PREFERRED)	', '44262'),
             ('F', 'COLONIAL PENN LIFE INS CO (STANDARD)	', '43779'),
             ('F', 'COLONIAL PENN LIFE INS CO (SUBSTANDARD)	', '44217'),
             ('F', 'COMPBENEFITS INS CO (PREFERRED)	', '46396'),
             ('F', 'COMPBENEFITS INS CO (STANDARD)	', '46401'),
             ('F', 'CONTINENTAL LIFE INS OF BRENTWOOD (PREFERRED)	', '42947'),
             ('F', 'CONTINENTAL LIFE INS OF BRENTWOOD (STANDARD)	', '42922'),
             ('F', 'ELIPS LIFE INS CO (PREFERRED)	', '42245'),
             ('F', 'ELIPS LIFE INS CO (STANDARD)	', '42250'),
             ('F', 'EPIC LIFE INS CO	', '44717'),
             ('F', 'ERIE FAMILY LIFE INS CO	', '46595'),
             ('F', 'ERIE FAMILY LIFE INS CO (TOBACCO)	', '46599'),
             ('F', 'FEDERAL LIFE INS CO	', '46562'),
             ('F', 'FEDERAL LIFE INS CO (TOBACCO)	', '46566'),
             ('F', 'FIRST HEALTH LIFE & HEALTH INS CO (PREFERRED)	', '44988'),
             ('F', 'FIRST HEALTH LIFE & HEALTH INS CO (STANDARD)	', '44993'),
             ('F', 'GLOBE LIFE & ACCIDENT INS CO	', '42968'),
             ('F', 'GLOBE LIFE & ACCIDENT INS CO	', '46047'),
             ('F', 'GLOBE LIFE & ACCIDENT INS CO (PREFERRED)	', '46042'),
             ('F', 'GREAT SOUTHERN LIFE INS CO	', '45739'),
             ('F', 'GREAT SOUTHERN LIFE INS CO (DIRECT TOBACCO)	', '46153'),
             ('F', 'GREAT SOUTHERN LIFE INS CO (DIRECT)	', '46289'),
             ('F', 'GREAT SOUTHERN LIFE INS CO (TOBACCO)	', '45637'),
             ('F', 'GUARANTEE TRUST LIFE INS CO (PREFERRED)	', '45086'),
             ('F', 'GUARANTEE TRUST LIFE INS CO (STANDARD)	', '45088'),
             ('F', 'HUMANA INS CO (HEALTHY LIVING PREFERRED)	', '45283'),
             ('F', 'HUMANA INS CO (HEALTHY LIVING STANDARD)	', '45278'),
             ('F', 'HUMANA INS CO (PREFERRED)	', '42961'),
             ('F', 'HUMANA INS CO (STANDARD)	', '42956'),
             ('F', 'HUMANADENTAL INS CO (PREFERRED)	', '44445'),
             ('F', 'HUMANADENTAL INS CO (STANDARD)	', '44439'),
             ('F', 'INDEPENDENCE AMERICAN INS CO	', '42027'),
             ('F', 'INDEPENDENCE AMERICAN INS CO (TOBACCO)	', '42031'),
             ('F', 'LUMICO LIFE INS CO (PREFERRED)	', '45705'),
             ('F', 'LUMICO LIFE INS CO (STANDARD)	', '45709'),
             ('F', 'MANHATTAN LIFE INS CO (PREFERRED)	', '43870'),
             ('F', 'MANHATTAN LIFE INS CO (STANDARD)	', '44380'),
             ('F', 'MANHATTANLIFE INS & ANNUITY CO (PREFERRED)	', '42019'),
             ('F', 'MANHATTANLIFE INS & ANNUITY CO (STANDARD)	', '42023'),
             ('F', 'MEDICO CORP LIFE INS CO	', '44250'),
             ('F', 'MEDICO CORP LIFE INS CO (PREFERRED)	', '44255'),
             ('F', 'MEDICO INS CO (PREFERRED)	', '42179'),
             ('F', 'MEDICO INS CO (PREFERRED)	', '43070'),
             ('F', 'MEDICO INS CO (STANDARD I)	', '42185'),
             ('F', 'MEDICO INS CO (STANDARD II)	', '42071'),
             ('F', 'MEDICO INS CO (STANDARD)	', '43067'),
             ('F', 'MUTUAL OF OMAHA INS CO	', '43516'),
             ('F', 'MUTUAL OF OMAHA INS CO (TOBACCO)	', '43509'),
             ('F', 'NASSAU LIFE INS CO OF KANSAS (PREFERRED)	', '46359'),
             ('F', 'NASSAU LIFE INS CO OF KANSAS (STANDARD)	', '46363'),
             ('F', 'NATIONAL GUARDIAN LIFE INS CO	', '45305'),
             ('F', 'NATIONAL GUARDIAN LIFE INS CO (TOBACCO)	', '45309'),
             ('F', 'NATIONAL HEALTH INS CO (PREFERRED II)	', '42632'),
             ('F', 'NATIONAL HEALTH INS CO (PREFERRED)	', '42619'),
             ('F', 'NATIONAL HEALTH INS CO (PREFERRED)	', '45928'),
             ('F', 'NATIONAL HEALTH INS CO (STANDARD)	', '42624'),
             ('F', 'NATIONAL HEALTH INS CO (STANDARD)	', '45933'),
             ('F', 'NEW ERA LIFE INS CO	', '42691'),
             ('F', 'NEW ERA LIFE INS CO (TOBACCO)	', '42750'),
             ('F', 'NEW ERA LIFE INS CO OF THE MIDWEST	', '42394'),
             ('F', 'NEW ERA LIFE INS CO OF THE MIDWEST	', '42762'),
             ('F', 'NEW ERA LIFE INS CO OF THE MIDWEST (TOBACCO)	', '42400'),
             ('F', 'NEW ERA LIFE INS CO OF THE MIDWEST (TOBACCO)	', '42757'),
             ('F', 'OMAHA INS CO	', '44267'),
             ('F', 'OMAHA INS CO (TOBACCO)	', '44270'),
             ('F', 'ORDER OF UNITED COMMERCIAL TRAVELERS	', '45240'),
             ('F', 'ORDER OF UNITED COMMERCIAL TRAVELERS (TOBACCO)	', '45968'),
             ('F', 'OXFORD LIFE INS CO	', '43761'),
             ('F', 'OXFORD LIFE INS CO (TOBACCO)	', '43762'),
             ('F', 'PAN-AMERICAN LIFE INS CO	', '45180'),
             ('F', 'PAN-AMERICAN LIFE INS CO (TOBACCO)	', '45920'),
             ('F', 'PEKIN LIFE INS CO	', '42646'),
             ('F', 'PEKIN LIFE INS CO (TOBACCO)	', '43900'),
             ('F', 'PHILADELPHIA AMERICAN LIFE INS	', '43179'),
             ('F', 'PHILADELPHIA AMERICAN LIFE INS (TOBACCO)	', '43524'),
             ('F', 'PHYSICIANS LIFE INS CO	', '46132'),
             ('F', 'PHYSICIANS LIFE INS CO	', '46259'),
             ('F', 'PHYSICIANS LIFE INS CO (TOBACCO)	', '46124'),
             ('F', 'PHYSICIANS LIFE INS CO (TOBACCO)	', '46128'),
             ('F', 'PURITAN LIFE INS CO OF AMERICA (PREFERRED)	', '44860'),
             ('F', 'PURITAN LIFE INS CO OF AMERICA (STANDARD)	', '44864'),
             ('F', 'RESERVE NATIONAL INS CO (PREFERRED)	', '43787'),
             ('F', 'RESERVE NATIONAL INS CO (STANDARD TOBACCO)	', '42721'),
             ('F', 'RESERVE NATIONAL INS CO (STANDARD)	', '42662'),
             ('F', 'RESOURCE LIFE INS CO	', '46009'),
             ('F', 'S. USA LIFE INS CO (PREFERRED)	', '44499'),
             ('F', 'S. USA LIFE INS CO (STANDARD)	', '44497'),
             ('F', 'SBLI USA LIFE INS CO (PREFERRED)	', '42337'),
             ('F', 'SBLI USA LIFE INS CO (STANDARD TOBACCO)	', '42277'),
             ('F', 'SBLI USA LIFE INS CO (STANDARD)	', '42273'),
             ('F', 'SHENANDOAH LIFE INS CO	', '44022'),
             ('F', 'SHENANDOAH LIFE INS CO (TOBACCO)	', '44026'),
             ('F', 'SILVERSCRIPT INS CO (PREFERRED)	', '46684'),
             ('F', 'SILVERSCRIPT INS CO (STANDARD)	', '46689'),
             ('F', 'SOUTHERN GUARANTY INS CO	', '46615'),
             ('F', 'SOUTHERN GUARANTY INS CO (TOBACCO)	', '46491'),
             ('F', 'STANDARD LIFE & CASUALTY INS CO	', '44002'),
             ('F', 'STANDARD LIFE & CASUALTY INS CO	', '46216'),
             ('F', 'STANDARD LIFE & CASUALTY INS CO (TOBACCO)	', '44006'),
             ('F', 'STANDARD LIFE & CASUALTY INS CO (TOBACCO)	', '46220'),
             ('F', 'STATE FARM MUTUAL AUTOMOBILE INS CO	', '42865'),
             ('F', 'STATE FARM MUTUAL AUTOMOBILE INS CO (TOBACCO)	', '44813'),
             ('F', 'STATE MUTUAL INS CO (BROKERAGE PREFERRED)	', '44476'),
             ('F', 'STATE MUTUAL INS CO (BROKERAGE STANDARD)	', '44467'),
             ('F', 'STATE MUTUAL INS CO (BRONZE)	', '42050'),
             ('F', 'STATE MUTUAL INS CO (DIRECT PREFERRED)	', '42833'),
             ('F', 'STATE MUTUAL INS CO (DIRECT STANDARD)	', '42687'),
             ('F', 'STATE MUTUAL INS CO (GOLD)	', '42151'),
             ('F', 'STATE MUTUAL INS CO (SELECT PREFERRED)	', '42792'),
             ('F', 'STATE MUTUAL INS CO (SELECT STANDARD)	', '42788'),
             ('F', 'STATE MUTUAL INS CO (SILVER)	', '42041'),
             ('F', 'TIER ONE INS CO (PREFERRED)	', '53658'),
             ('F', 'TIER ONE INS CO (STANDARD)	', '53567'),
             ('F', 'TRANSAMERICA LIFE INS CO	', '43985'),
             ('F', 'TRANSAMERICA LIFE INS CO (TOBACCO)	', '43995'),
             ('F', 'UNIFIED LIFE INS CO (PREFERRED)	', '45020'),
             ('F', 'UNIFIED LIFE INS CO (STANDARD)	', '45025'),
             ('F', 'UNION SECURITY INS CO (PREFERRED)	', '45695'),
             ('F', 'UNION SECURITY INS CO (STANDARD)	', '45699'),
             ('F', 'UNITED AMERICAN INS CO (PREFERRED)	', '43371'),
             ('F', 'UNITED AMERICAN INS CO (STANDARD)	', '43444'),
             ('F', 'UNITED INSURANCE COMPANY OF AMERICA (PREFERRED)	', '42058'),
             ('F', 'UNITED INSURANCE COMPANY OF AMERICA (STANDARD)	', '42064'),
             ('F', 'UNITED NATIONAL LIFE INS CO OF AMERICA (PREFERRED)	', '43582'),
             ('F', 'UNITED NATIONAL LIFE INS CO OF AMERICA (STANDARD)	', '43586'),
             ('F', 'UNITED OF OMAHA	', '43521'),
             ('F', 'UNITED OF OMAHA (TOBACCO)	', '43474'),
             ('F', 'UNITED STATES FIRE INS CO (PREFERRED)	', '46326'),
             ('F', 'UNITED STATES FIRE INS CO (STANDARD)	', '46334'),
             ('F', 'UNITED WORLD LIFE INS CO	', '43386'),
             ('F', 'UNITED WORLD LIFE INS CO (TOBACCO)	', '43315'),
             ('F', 'UNITEDHEALTHCARE	', '44672'),
             ('F', 'UNITEDHEALTHCARE (DISCOUNT)	', '44758'),
             ('F', 'UNITEDHEALTHCARE (LEVEL 1)	', '44594'),
             ('F', 'UNITEDHEALTHCARE (LEVEL 2)	', '44602'),
             ('F', 'UNITEDHEALTHCARE (LEVEL 2)	', '44680'),
             ('F', 'UNITEDHEALTHCARE (SELECT DISCOUNT)	', '44978'),
             ('F', 'UNITEDHEALTHCARE (SELECT LEVEL 1)	', '45579'),
             ('F', 'UNITEDHEALTHCARE (SELECT LEVEL 2)	', '45577'),
             ('F', 'UNITEDHEALTHCARE (SELECT LEVEL 2)	', '45581'),
             ('F', 'UNITEDHEALTHCARE (SELECT TOBACCO DISCOUNT)	', '45591'),
             ('F', 'UNITEDHEALTHCARE (SELECT TOBACCO LEVEL 1)	', '45585'),
             ('F', 'UNITEDHEALTHCARE (SELECT TOBACCO LEVEL 2)	', '45583'),
             ('F', 'UNITEDHEALTHCARE (SELECT TOBACCO LEVEL 2)	', '45587'),
             ('F', 'UNITEDHEALTHCARE (SELECT TOBACCO)	', '45589'),
             ('F', 'UNITEDHEALTHCARE (SELECT)	', '44980'),
             ('F', 'UNITEDHEALTHCARE (TOBACCO DISCOUNT)	', '44516'),
             ('F', 'UNITEDHEALTHCARE (TOBACCO LEVEL 1)	', '45121'),
             ('F', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '44972'),
             ('F', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '45113'),
             ('F', 'UNITEDHEALTHCARE (TOBACCO)	', '45139'),
             ('F', 'USAA LIFE INSURANCE COMPANY	', '42723'),
             ('F', 'USAA LIFE INSURANCE COMPANY (TOBACCO)	', '42872'),
             ('F', 'WASHINGTON NATIONAL INS CO (PREFERRED)	', '53710'),
             ('F', 'WASHINGTON NATIONAL INS CO (STANDARD)	', '53648'),
             ('F', 'WASHINGTON NATIONAL INS CO (SUBSTANDARD)	', '53659'),
             ('F', 'WESTERN UNITED LIFE ASR CO (PREFERRED)	', '45599'),
             ('F', 'WESTERN UNITED LIFE ASR CO (STANDARD)	', '45598'),
             ('FH', 'AETNA HEALTH & LIFE INS CO (PREFERRED)	', '44242'),
             ('FH', 'AETNA HEALTH & LIFE INS CO (STANDARD)	', '44293'),
             ('FH', 'AMERICAN CONTINENTAL INS CO (PREFERRED)	', '43201'),
             ('FH', 'AMERICAN CONTINENTAL INS CO (STANDARD)	', '43203'),
             ('FH', 'AMERICAN REPUBLIC CORP INS CO	', '43728'),
             ('FH', 'AMERICAN REPUBLIC CORP INS CO (PREFERRED)	', '43729'),
             ('FH', 'BANKERS FIDELITY ASSURANCE CO (PREFERRED)	', '43929'),
             ('FH', 'BANKERS FIDELITY ASSURANCE CO (STANDARD)	', '44454'),
             ('FH', 'BANKERS FIDELITY LIFE INS CO (PREFERRED)	', '43639'),
             ('FH', 'BANKERS FIDELITY LIFE INS CO (STANDARD)	', '43714'),
             ('FH', 'CIGNA HEALTH & LIFE INS CO (PREFERRED)	', '44645'),
             ('FH', 'CIGNA HEALTH & LIFE INS CO (STANDARD)	', '44640'),
             ('FH', 'COLONIAL PENN LIFE INS CO (PREFERRED)	', '44263'),
             ('FH', 'COLONIAL PENN LIFE INS CO (STANDARD)	', '43780'),
             ('FH', 'COLONIAL PENN LIFE INS CO (SUBSTANDARD)	', '44218'),
             ('FH', 'GLOBE LIFE & ACCIDENT INS CO	', '44079'),
             ('FH', 'GREAT SOUTHERN LIFE INS CO	', '45740'),
             ('FH', 'GREAT SOUTHERN LIFE INS CO (TOBACCO)	', '45638'),
             ('FH', 'HUMANA INS CO (HEALTHY LIVING PREFERRED)	', '45284'),
             ('FH', 'HUMANA INS CO (HEALTHY LIVING STANDARD)	', '45279'),
             ('FH', 'HUMANA INS CO (PREFERRED)	', '42962'),
             ('FH', 'HUMANA INS CO (STANDARD)	', '42957'),
             ('FH', 'HUMANADENTAL INS CO (PREFERRED)	', '44446'),
             ('FH', 'HUMANADENTAL INS CO (STANDARD)	', '44440'),
             ('FH', 'MEDICO INS CO (PREFERRED)	', '42180'),
             ('FH', 'MEDICO INS CO (STANDARD I)	', '42186'),
             ('FH', 'MEDICO INS CO (STANDARD II)	', '42072'),
             ('FH', 'NATIONAL HEALTH INS CO (PREFERRED II)	', '42633'),
             ('FH', 'NATIONAL HEALTH INS CO (PREFERRED)	', '42620'),
             ('FH', 'NATIONAL HEALTH INS CO (PREFERRED)	', '45929'),
             ('FH', 'NATIONAL HEALTH INS CO (STANDARD)	', '42625'),
             ('FH', 'NATIONAL HEALTH INS CO (STANDARD)	', '45791'),
             ('FH', 'NEW ERA LIFE INS CO	', '42743'),
             ('FH', 'NEW ERA LIFE INS CO (TOBACCO)	', '42752'),
             ('FH', 'NEW ERA LIFE INS CO OF THE MIDWEST	', '42395'),
             ('FH', 'NEW ERA LIFE INS CO OF THE MIDWEST	', '42764'),
             ('FH', 'NEW ERA LIFE INS CO OF THE MIDWEST (TOBACCO)	', '42402'),
             ('FH', 'NEW ERA LIFE INS CO OF THE MIDWEST (TOBACCO)	', '42765'),
             ('FH', 'OMAHA INS CO	', '44552'),
             ('FH', 'OMAHA INS CO (TOBACCO)	', '44554'),
             ('FH', 'PHYSICIANS LIFE INS CO	', '46120'),
             ('FH', 'PHYSICIANS LIFE INS CO	', '46133'),
             ('FH', 'PHYSICIANS LIFE INS CO (TOBACCO)	', '46125'),
             ('FH', 'PHYSICIANS LIFE INS CO (TOBACCO)	', '46129'),
             ('FH', 'RESERVE NATIONAL INS CO (PREFERRED)	', '43788'),
             ('FH', 'RESERVE NATIONAL INS CO (STANDARD)	', '43214'),
             ('FH', 'STATE MUTUAL INS CO (BROKERAGE PREFERRED)	', '44477'),
             ('FH', 'STATE MUTUAL INS CO (BROKERAGE STANDARD)	', '44468'),
             ('FH', 'STATE MUTUAL INS CO (BRONZE)	', '42051'),
             ('FH', 'STATE MUTUAL INS CO (DIRECT PREFERRED)	', '43687'),
             ('FH', 'STATE MUTUAL INS CO (DIRECT STANDARD)	', '43682'),
             ('FH', 'STATE MUTUAL INS CO (GOLD)	', '42152'),
             ('FH', 'STATE MUTUAL INS CO (SILVER)	', '42042'),
             ('FH', 'UNIFIED LIFE INS CO (PREFERRED)	', '45021'),
             ('FH', 'UNIFIED LIFE INS CO (STANDARD)	', '45026'),
             ('FH', 'UNITED AMERICAN INS CO (PREFERRED)	', '43372'),
             ('FH', 'UNITED AMERICAN INS CO (STANDARD)	', '43445'),
             ('G', 'ACCENDO INS CO (PREFERRED)	', '46428'),
             ('G', 'ACCENDO INS CO (STANDARD)	', '46432'),
             ('G', 'ACE PROPERTY & CASUALTY INS CO (PREFERRED)	', '53436'),
             ('G', 'ACE PROPERTY & CASUALTY INS CO (STANDARD)	', '53562'),
             ('G', 'AETNA HEALTH & LIFE INS CO (PREFERRED)	', '44243'),
             ('G', 'AETNA HEALTH & LIFE INS CO (STANDARD)	', '44294'),
             ('G', 'AETNA LIFE INS CO	', '43648'),
             ('G', 'AMERICAN BENEFIT LIFE INS CO (PREFERRED)	', '42518'),
             ('G', 'AMERICAN BENEFIT LIFE INS CO (STANDARD)	', '42440'),
             ('G', 'AMERICAN CONTINENTAL INS CO (PREFERRED)	', '43087'),
             ('G', 'AMERICAN CONTINENTAL INS CO (STANDARD)	', '43094'),
             ('G', 'AMERICAN HOME LIFE INS CO (PREFERRED)	', '53501'),
             ('G', 'AMERICAN HOME LIFE INS CO (STANDARD)	', '53671'),
             ('G', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO	', '44899'),
             ('G', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO	', '45770'),
             ('G', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO (TOBACCO)	', '44903'),
             ('G', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO (TOBACCO)	', '45774'),
             ('G', 'ASSURED LIFE ASSN	', '43220'),
             ('G', 'ASSURED LIFE ASSN (TOBACCO)	', '43226'),
             ('G', 'ATLANTIC COAST LIFE INS CO	', '45732'),
             ('G', 'ATLANTIC COAST LIFE INS CO (TOBACCO)	', '45736'),
             ('G', 'BANKERS FIDELITY ASSURANCE CO (PREFERRED)	', '45078'),
             ('G', 'BANKERS FIDELITY ASSURANCE CO (STANDARD)	', '45077'),
             ('G', 'BANKERS FIDELITY LIFE INS CO (PREFERRED)	', '43692'),
             ('G', 'BANKERS FIDELITY LIFE INS CO (STANDARD)	', '43690'),
             ('G', 'BANKERS RESERVE LIFE INS CO OF WISCONSIN	', '53758'),
             ('G', 'BANKERS RESERVE LIFE INS CO OF WISCONSIN (TOBACCO)	', '53747'),
             ('G', 'BLUECROSS BLUESHIELD OF TENNESSEE	', '45082'),
             ('G', 'BLUECROSS BLUESHIELD OF TENNESSEE (TOBACCO)	', '45084'),
             ('G', 'CAPITOL LIFE INS CO (PREFERRED)	', '46268'),
             ('G', 'CAPITOL LIFE INS CO (STANDARD)	', '46272'),
             ('G', 'CENTRAL STATES HEALTH & LIFE OF OMAHA (PREFERRED)	', '45458'),
             ('G', 'CENTRAL STATES HEALTH & LIFE OF OMAHA (STANDARD)	', '45331'),
             ('G', 'CIGNA HEALTH & LIFE INS CO (PREFERRED)	', '44646'),
             ('G', 'CIGNA HEALTH & LIFE INS CO (STANDARD)	', '44641'),
             ('G', 'CIGNA NATIONAL HEALTH INS CO (PREFERRED)	', '46055'),
             ('G', 'CIGNA NATIONAL HEALTH INS CO (STANDARD II)	', '42108'),
             ('G', 'CIGNA NATIONAL HEALTH INS CO (STANDARD III)	', '42112'),
             ('G', 'CIGNA NATIONAL HEALTH INS CO (STANDARD)	', '42104'),
             ('G', 'COLONIAL PENN LIFE INS CO (PREFERRED)	', '44264'),
             ('G', 'COLONIAL PENN LIFE INS CO (STANDARD)	', '43781'),
             ('G', 'COLONIAL PENN LIFE INS CO (SUBSTANDARD)	', '44219'),
             ('G', 'COMPBENEFITS INS CO (PREFERRED)	', '46397'),
             ('G', 'COMPBENEFITS INS CO (STANDARD)	', '46402'),
             ('G', 'CONTINENTAL LIFE INS OF BRENTWOOD (PREFERRED)	', '42898'),
             ('G', 'CONTINENTAL LIFE INS OF BRENTWOOD (STANDARD)	', '42900'),
             ('G', 'ELIPS LIFE INS CO (PREFERRED)	', '42246'),
             ('G', 'ELIPS LIFE INS CO (STANDARD)	', '42251'),
             ('G', 'EPIC LIFE INS CO	', '45290'),
             ('G', 'ERIE FAMILY LIFE INS CO	', '46596'),
             ('G', 'ERIE FAMILY LIFE INS CO (TOBACCO)	', '46460'),
             ('G', 'FEDERAL LIFE INS CO	', '46563'),
             ('G', 'FEDERAL LIFE INS CO (TOBACCO)	', '46567'),
             ('G', 'FIRST HEALTH LIFE & HEALTH INS CO (PREFERRED)	', '44989'),
             ('G', 'FIRST HEALTH LIFE & HEALTH INS CO (STANDARD)	', '44994'),
             ('G', 'GLOBE LIFE & ACCIDENT INS CO	', '45068'),
             ('G', 'GLOBE LIFE & ACCIDENT INS CO	', '46048'),
             ('G', 'GLOBE LIFE & ACCIDENT INS CO (PREFERRED)	', '46043'),
             ('G', 'GREAT SOUTHERN LIFE INS CO	', '45741'),
             ('G', 'GREAT SOUTHERN LIFE INS CO (DIRECT TOBACCO)	', '46154'),
             ('G', 'GREAT SOUTHERN LIFE INS CO (DIRECT)	', '46290'),
             ('G', 'GREAT SOUTHERN LIFE INS CO (TOBACCO)	', '45639'),
             ('G', 'GUARANTEE TRUST LIFE INS CO (PREFERRED)	', '45087'),
             ('G', 'GUARANTEE TRUST LIFE INS CO (STANDARD)	', '45089'),
             ('G', 'HUMANADENTAL INS CO (PREFERRED)	', '44447'),
             ('G', 'HUMANADENTAL INS CO (STANDARD)	', '44441'),
             ('G', 'INDEPENDENCE AMERICAN INS CO	', '42028'),
             ('G', 'INDEPENDENCE AMERICAN INS CO (TOBACCO)	', '46680'),
             ('G', 'LUMICO LIFE INS CO (PREFERRED)	', '45706'),
             ('G', 'LUMICO LIFE INS CO (STANDARD)	', '45710'),
             ('G', 'MANHATTAN LIFE INS CO (PREFERRED)	', '43871'),
             ('G', 'MANHATTAN LIFE INS CO (STANDARD)	', '44381'),
             ('G', 'MANHATTANLIFE INS & ANNUITY CO (PREFERRED)	', '42020'),
             ('G', 'MANHATTANLIFE INS & ANNUITY CO (STANDARD)	', '42024'),
             ('G', 'MEDICO CORP LIFE INS CO	', '44252'),
             ('G', 'MEDICO CORP LIFE INS CO (PREFERRED)	', '44160'),
             ('G', 'MEDICO INS CO (PREFERRED)	', '42181'),
             ('G', 'MEDICO INS CO (PREFERRED)	', '43708'),
             ('G', 'MEDICO INS CO (STANDARD I)	', '42187'),
             ('G', 'MEDICO INS CO (STANDARD II)	', '42073'),
             ('G', 'MEDICO INS CO (STANDARD)	', '43706'),
             ('G', 'MUTUAL OF OMAHA INS CO	', '43517'),
             ('G', 'MUTUAL OF OMAHA INS CO (TOBACCO)	', '43510'),
             ('G', 'NASSAU LIFE INS CO OF KANSAS (PREFERRED)	', '46360'),
             ('G', 'NASSAU LIFE INS CO OF KANSAS (STANDARD)	', '46364'),
             ('G', 'NATIONAL GUARDIAN LIFE INS CO	', '45306'),
             ('G', 'NATIONAL GUARDIAN LIFE INS CO (TOBACCO)	', '45310'),
             ('G', 'NATIONAL HEALTH INS CO (PREFERRED II)	', '42634'),
             ('G', 'NATIONAL HEALTH INS CO (PREFERRED)	', '42621'),
             ('G', 'NATIONAL HEALTH INS CO (PREFERRED)	', '45930'),
             ('G', 'NATIONAL HEALTH INS CO (STANDARD)	', '42626'),
             ('G', 'NATIONAL HEALTH INS CO (STANDARD)	', '45792'),
             ('G', 'NEW ERA LIFE INS CO	', '42692'),
             ('G', 'NEW ERA LIFE INS CO (TOBACCO)	', '42751'),
             ('G', 'NEW ERA LIFE INS CO OF THE MIDWEST	', '42396'),
             ('G', 'NEW ERA LIFE INS CO OF THE MIDWEST	', '42763'),
             ('G', 'NEW ERA LIFE INS CO OF THE MIDWEST (TOBACCO)	', '42403'),
             ('G', 'NEW ERA LIFE INS CO OF THE MIDWEST (TOBACCO)	', '42758'),
             ('G', 'OMAHA INS CO	', '44268'),
             ('G', 'OMAHA INS CO (TOBACCO)	', '44271'),
             ('G', 'ORDER OF UNITED COMMERCIAL TRAVELERS	', '45241'),
             ('G', 'ORDER OF UNITED COMMERCIAL TRAVELERS (TOBACCO)	', '45969'),
             ('G', 'OXFORD LIFE INS CO	', '44722'),
             ('G', 'OXFORD LIFE INS CO (TOBACCO)	', '44723'),
             ('G', 'PAN-AMERICAN LIFE INS CO	', '45181'),
             ('G', 'PAN-AMERICAN LIFE INS CO (TOBACCO)	', '45921'),
             ('G', 'PEKIN LIFE INS CO	', '44276'),
             ('G', 'PEKIN LIFE INS CO (TOBACCO)	', '43902'),
             ('G', 'PHILADELPHIA AMERICAN LIFE INS	', '43377'),
             ('G', 'PHILADELPHIA AMERICAN LIFE INS (TOBACCO)	', '43381'),
             ('G', 'PHYSICIANS LIFE INS CO	', '46121'),
             ('G', 'PHYSICIANS LIFE INS CO	', '46134'),
             ('G', 'PHYSICIANS LIFE INS CO (TOBACCO)	', '46126'),
             ('G', 'PHYSICIANS LIFE INS CO (TOBACCO)	', '46130'),
             ('G', 'PURITAN LIFE INS CO OF AMERICA (PREFERRED)	', '44861'),
             ('G', 'PURITAN LIFE INS CO OF AMERICA (STANDARD)	', '44865'),
             ('G', 'RESERVE NATIONAL INS CO (PREFERRED TOBACCO)	', '44378'),
             ('G', 'RESERVE NATIONAL INS CO (PREFERRED)	', '44377'),
             ('G', 'RESERVE NATIONAL INS CO (STANDARD TOBACCO)	', '44376'),
             ('G', 'RESERVE NATIONAL INS CO (STANDARD)	', '44375'),
             ('G', 'RESOURCE LIFE INS CO	', '46010'),
             ('G', 'S. USA LIFE INS CO (PREFERRED)	', '45669'),
             ('G', 'S. USA LIFE INS CO (STANDARD)	', '45668'),
             ('G', 'SBLI USA LIFE INS CO (PREFERRED)	', '42270'),
             ('G', 'SBLI USA LIFE INS CO (STANDARD TOBACCO)	', '42278'),
             ('G', 'SBLI USA LIFE INS CO (STANDARD)	', '42274'),
             ('G', 'SHENANDOAH LIFE INS CO	', '44023'),
             ('G', 'SHENANDOAH LIFE INS CO (TOBACCO)	', '44027'),
             ('G', 'SILVERSCRIPT INS CO (PREFERRED)	', '46685'),
             ('G', 'SILVERSCRIPT INS CO (STANDARD)	', '46690'),
             ('G', 'SOUTHERN GUARANTY INS CO	', '46488'),
             ('G', 'SOUTHERN GUARANTY INS CO (TOBACCO)	', '46492'),
             ('G', 'STANDARD LIFE & CASUALTY INS CO	', '44003'),
             ('G', 'STANDARD LIFE & CASUALTY INS CO	', '46217'),
             ('G', 'STANDARD LIFE & CASUALTY INS CO (TOBACCO)	', '44007'),
             ('G', 'STANDARD LIFE & CASUALTY INS CO (TOBACCO)	', '46221'),
             ('G', 'STATE FARM MUTUAL AUTOMOBILE INS CO	', '45827'),
             ('G', 'STATE FARM MUTUAL AUTOMOBILE INS CO (TOBACCO)	', '45830'),
             ('G', 'STATE MUTUAL INS CO (BROKERAGE PREFERRED)	', '44478'),
             ('G', 'STATE MUTUAL INS CO (BROKERAGE STANDARD)	', '44469'),
             ('G', 'STATE MUTUAL INS CO (BRONZE)	', '46712'),
             ('G', 'STATE MUTUAL INS CO (DIRECT PREFERRED)	', '42901'),
             ('G', 'STATE MUTUAL INS CO (DIRECT STANDARD)	', '42903'),
             ('G', 'STATE MUTUAL INS CO (GOLD)	', '42153'),
             ('G', 'STATE MUTUAL INS CO (SILVER)	', '42043'),
             ('G', 'TIER ONE INS CO (PREFERRED)	', '53494'),
             ('G', 'TIER ONE INS CO (STANDARD)	', '53427'),
             ('G', 'TRANSAMERICA LIFE INS CO	', '43986'),
             ('G', 'TRANSAMERICA LIFE INS CO (TOBACCO)	', '43996'),
             ('G', 'TRH HEALTH INS CO	', '42477'),
             ('G', 'TRH HEALTH INS CO (TOBACCO)	', '42481'),
             ('G', 'UNIFIED LIFE INS CO (PREFERRED)	', '45022'),
             ('G', 'UNIFIED LIFE INS CO (STANDARD)	', '45027'),
             ('G', 'UNION SECURITY INS CO (PREFERRED)	', '45696'),
             ('G', 'UNION SECURITY INS CO (STANDARD)	', '45700'),
             ('G', 'UNITED AMERICAN INS CO (PREFERRED)	', '43373'),
             ('G', 'UNITED AMERICAN INS CO (STANDARD)	', '43446'),
             ('G', 'UNITED INSURANCE COMPANY OF AMERICA (PREFERRED)	', '42059'),
             ('G', 'UNITED INSURANCE COMPANY OF AMERICA (STANDARD)	', '42065'),
             ('G', 'UNITED NATIONAL LIFE INS CO OF AMERICA (PREFERRED)	', '43583'),
             ('G', 'UNITED NATIONAL LIFE INS CO OF AMERICA (STANDARD)	', '43587'),
             ('G', 'UNITED OF OMAHA	', '43522'),
             ('G', 'UNITED OF OMAHA (TOBACCO)	', '43475'),
             ('G', 'UNITED STATES FIRE INS CO (PREFERRED)	', '46327'),
             ('G', 'UNITED STATES FIRE INS CO (STANDARD)	', '46196'),
             ('G', 'UNITED WORLD LIFE INS CO	', '43387'),
             ('G', 'UNITED WORLD LIFE INS CO (TOBACCO)	', '43316'),
             ('G', 'UNITEDHEALTHCARE	', '44673'),
             ('G', 'UNITEDHEALTHCARE (DISCOUNT)	', '44759'),
             ('G', 'UNITEDHEALTHCARE (LEVEL 1)	', '44595'),
             ('G', 'UNITEDHEALTHCARE (LEVEL 2)	', '44603'),
             ('G', 'UNITEDHEALTHCARE (LEVEL 2)	', '44681'),
             ('G', 'UNITEDHEALTHCARE (SELECT DISCOUNT)	', '46184'),
             ('G', 'UNITEDHEALTHCARE (SELECT LEVEL 1)	', '46036'),
             ('G', 'UNITEDHEALTHCARE (SELECT LEVEL 2)	', '46170'),
             ('G', 'UNITEDHEALTHCARE (SELECT LEVEL 2)	', '46188'),
             ('G', 'UNITEDHEALTHCARE (SELECT TOBACCO DISCOUNT)	', '46190'),
             ('G', 'UNITEDHEALTHCARE (SELECT TOBACCO LEVEL 1)	', '46038'),
             ('G', 'UNITEDHEALTHCARE (SELECT TOBACCO LEVEL 2)	', '46174'),
             ('G', 'UNITEDHEALTHCARE (SELECT TOBACCO LEVEL 2)	', '46192'),
             ('G', 'UNITEDHEALTHCARE (SELECT TOBACCO)	', '46172'),
             ('G', 'UNITEDHEALTHCARE (SELECT)	', '46168'),
             ('G', 'UNITEDHEALTHCARE (TOBACCO DISCOUNT)	', '44517'),
             ('G', 'UNITEDHEALTHCARE (TOBACCO LEVEL 1)	', '45122'),
             ('G', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '44973'),
             ('G', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '45114'),
             ('G', 'UNITEDHEALTHCARE (TOBACCO)	', '45140'),
             ('G', 'USAA LIFE INSURANCE COMPANY	', '42724'),
             ('G', 'USAA LIFE INSURANCE COMPANY (TOBACCO)	', '42873'),
             ('G', 'WASHINGTON NATIONAL INS CO (PREFERRED)	', '53512'),
             ('G', 'WASHINGTON NATIONAL INS CO (STANDARD)	', '53416'),
             ('G', 'WASHINGTON NATIONAL INS CO (SUBSTANDARD)	', '53678'),
             ('G', 'WESTERN UNITED LIFE ASR CO (PREFERRED)	', '44734'),
             ('G', 'WESTERN UNITED LIFE ASR CO (STANDARD)	', '44730'),
             ('GH', 'ACE PROPERTY & CASUALTY INS CO (PREFERRED)	', '53582'),
             ('GH', 'ACE PROPERTY & CASUALTY INS CO (STANDARD)	', '53670'),
             ('GH', 'COLONIAL PENN LIFE INS CO (PREFERRED)	', '46306'),
             ('GH', 'COLONIAL PENN LIFE INS CO (STANDARD)	', '46305'),
             ('GH', 'COLONIAL PENN LIFE INS CO (SUBSTANDARD)	', '46307'),
             ('GH', 'COMPBENEFITS INS CO (PREFERRED)	', '46398'),
             ('GH', 'COMPBENEFITS INS CO (STANDARD)	', '46403'),
             ('GH', 'CONTINENTAL LIFE INS OF BRENTWOOD (PREFERRED)	', '46246'),
             ('GH', 'CONTINENTAL LIFE INS OF BRENTWOOD (STANDARD)	', '46247'),
             ('GH', 'ELIPS LIFE INS CO (PREFERRED)	', '42247'),
             ('GH', 'ELIPS LIFE INS CO (STANDARD)	', '42252'),
             ('GH', 'FEDERAL LIFE INS CO	', '46447'),
             ('GH', 'FEDERAL LIFE INS CO (TOBACCO)	', '46450'),
             ('GH', 'GLOBE LIFE & ACCIDENT INS CO	', '46049'),
             ('GH', 'GLOBE LIFE & ACCIDENT INS CO (PREFERRED)	', '46044'),
             ('GH', 'HUMANADENTAL INS CO (PREFERRED)	', '46626'),
             ('GH', 'HUMANADENTAL INS CO (STANDARD)	', '46625'),
             ('GH', 'MEDICO INS CO (PREFERRED)	', '42182'),
             ('GH', 'MEDICO INS CO (STANDARD I)	', '42068'),
             ('GH', 'MEDICO INS CO (STANDARD II)	', '42074'),
             ('GH', 'NEW ERA LIFE INS CO OF THE MIDWEST	', '42397'),
             ('GH', 'NEW ERA LIFE INS CO OF THE MIDWEST (TOBACCO)	', '42322'),
             ('GH', 'PHYSICIANS LIFE INS CO	', '46122'),
             ('GH', 'PHYSICIANS LIFE INS CO	', '46135'),
             ('GH', 'PHYSICIANS LIFE INS CO (TOBACCO)	', '46127'),
             ('GH', 'PHYSICIANS LIFE INS CO (TOBACCO)	', '46131'),
             ('GH', 'UNITED AMERICAN INS CO (PREFERRED)	', '46620'),
             ('GH', 'UNITED AMERICAN INS CO (STANDARD)	', '46619'),
             ('GH', 'UNITED INSURANCE COMPANY OF AMERICA (PREFERRED)	', '42060'),
             ('GH', 'UNITED INSURANCE COMPANY OF AMERICA (STANDARD)	', '42066'),
             ('GH', 'UNITED STATES FIRE INS CO (PREFERRED)	', '46328'),
             ('GH', 'UNITED STATES FIRE INS CO (STANDARD)	', '46197'),
             ('GH', 'UNITED WORLD LIFE INS CO	', '46481'),
             ('GH', 'UNITED WORLD LIFE INS CO (TOBACCO)	', '46482'),
             ('GH', 'WASHINGTON NATIONAL INS CO (PREFERRED)	', '53540'),
             ('GH', 'WASHINGTON NATIONAL INS CO (STANDARD)	', '53727'),
             ('GH', 'WASHINGTON NATIONAL INS CO (SUBSTANDARD)	', '53471'),
             ('K', 'AMERICAN REPUBLIC CORP INS CO	', '43258'),
             ('K', 'AMERICAN REPUBLIC CORP INS CO (PREFERRED)	', '43262'),
             ('K', 'BANKERS FIDELITY LIFE INS CO (PREFERRED)	', '43693'),
             ('K', 'BANKERS FIDELITY LIFE INS CO (STANDARD)	', '43691'),
             ('K', 'COLONIAL PENN LIFE INS CO (PREFERRED)	', '44265'),
             ('K', 'COLONIAL PENN LIFE INS CO (STANDARD)	', '43782'),
             ('K', 'COLONIAL PENN LIFE INS CO (SUBSTANDARD)	', '44220'),
             ('K', 'EPIC LIFE INS CO	', '44624'),
             ('K', 'HUMANA INS CO (HEALTHY LIVING PREFERRED)	', '45285'),
             ('K', 'HUMANA INS CO (HEALTHY LIVING STANDARD)	', '45280'),
             ('K', 'HUMANA INS CO (PREFERRED)	', '43143'),
             ('K', 'HUMANA INS CO (STANDARD)	', '43141'),
             ('K', 'TRANSAMERICA LIFE INS CO	', '43987'),
             ('K', 'TRANSAMERICA LIFE INS CO (TOBACCO)	', '43997'),
             ('K', 'UNITED AMERICAN INS CO (PREFERRED)	', '43001'),
             ('K', 'UNITED AMERICAN INS CO (STANDARD)	', '42999'),
             ('K', 'UNITED STATES FIRE INS CO (PREFERRED)	', '46329'),
             ('K', 'UNITED STATES FIRE INS CO (STANDARD)	', '46198'),
             ('K', 'UNITEDHEALTHCARE	', '44674'),
             ('K', 'UNITEDHEALTHCARE (DISCOUNT)	', '44666'),
             ('K', 'UNITEDHEALTHCARE (LEVEL 1)	', '44596'),
             ('K', 'UNITEDHEALTHCARE (LEVEL 2)	', '44510'),
             ('K', 'UNITEDHEALTHCARE (LEVEL 2)	', '44588'),
             ('K', 'UNITEDHEALTHCARE (TOBACCO DISCOUNT)	', '44518'),
             ('K', 'UNITEDHEALTHCARE (TOBACCO LEVEL 1)	', '44966'),
             ('K', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '44974'),
             ('K', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '45115'),
             ('K', 'UNITEDHEALTHCARE (TOBACCO)	', '45107'),
             ('L', 'AMERICAN REPUBLIC CORP INS CO	', '43259'),
             ('L', 'AMERICAN REPUBLIC CORP INS CO (PREFERRED)	', '43263'),
             ('L', 'COLONIAL PENN LIFE INS CO (PREFERRED)	', '44178'),
             ('L', 'COLONIAL PENN LIFE INS CO (STANDARD)	', '43783'),
             ('L', 'COLONIAL PENN LIFE INS CO (SUBSTANDARD)	', '44221'),
             ('L', 'EPIC LIFE INS CO	', '44625'),
             ('L', 'HUMANA INS CO (PREFERRED)	', '43144'),
             ('L', 'HUMANA INS CO (STANDARD)	', '43142'),
             ('L', 'TRANSAMERICA LIFE INS CO	', '43988'),
             ('L', 'TRANSAMERICA LIFE INS CO (TOBACCO)	', '43998'),
             ('L', 'UNITED AMERICAN INS CO (PREFERRED)	', '43002'),
             ('L', 'UNITED AMERICAN INS CO (STANDARD)	', '43000'),
             ('L', 'UNITED STATES FIRE INS CO (PREFERRED)	', '46330'),
             ('L', 'UNITED STATES FIRE INS CO (STANDARD)	', '46199'),
             ('L', 'UNITEDHEALTHCARE	', '44675'),
             ('L', 'UNITEDHEALTHCARE (DISCOUNT)	', '44667'),
             ('L', 'UNITEDHEALTHCARE (LEVEL 1)	', '44597'),
             ('L', 'UNITEDHEALTHCARE (LEVEL 2)	', '44511'),
             ('L', 'UNITEDHEALTHCARE (LEVEL 2)	', '44589'),
             ('L', 'UNITEDHEALTHCARE (TOBACCO DISCOUNT)	', '44519'),
             ('L', 'UNITEDHEALTHCARE (TOBACCO LEVEL 1)	', '44967'),
             ('L', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '44975'),
             ('L', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '45116'),
             ('L', 'UNITEDHEALTHCARE (TOBACCO)	', '45108'),
             ('M', 'COLONIAL PENN LIFE INS CO (PREFERRED)	', '44179'),
             ('M', 'COLONIAL PENN LIFE INS CO (STANDARD)	', '43784'),
             ('M', 'COLONIAL PENN LIFE INS CO (SUBSTANDARD)	', '44222'),
             ('M', 'NEW ERA LIFE INS CO OF THE MIDWEST	', '53474'),
             ('M', 'NEW ERA LIFE INS CO OF THE MIDWEST (TOBACCO)	', '53431'),
             ('M', 'STATE MUTUAL INS CO (BROKERAGE PREFERRED)	', '44479'),
             ('M', 'STATE MUTUAL INS CO (BROKERAGE STANDARD)	', '44470'),
             ('M', 'STATE MUTUAL INS CO (BRONZE)	', '46713'),
             ('M', 'STATE MUTUAL INS CO (DIRECT PREFERRED)	', '43685'),
             ('M', 'STATE MUTUAL INS CO (DIRECT STANDARD)	', '43683'),
             ('M', 'STATE MUTUAL INS CO (GOLD)	', '42154'),
             ('M', 'STATE MUTUAL INS CO (SILVER)	', '42044'),
             ('M', 'TRANSAMERICA LIFE INS CO	', '43989'),
             ('M', 'TRANSAMERICA LIFE INS CO (TOBACCO)	', '43999'),
             ('M', 'UNITED OF OMAHA	', '43523'),
             ('M', 'UNITED OF OMAHA (TOBACCO)	', '43476'),
             ('N', 'ACCENDO INS CO (PREFERRED)	', '46429'),
             ('N', 'ACCENDO INS CO (STANDARD)	', '46433'),
             ('N', 'ACE PROPERTY & CASUALTY INS CO (PREFERRED)	', '53535'),
             ('N', 'ACE PROPERTY & CASUALTY INS CO (STANDARD)	', '53640'),
             ('N', 'AETNA HEALTH & LIFE INS CO (PREFERRED)	', '44244'),
             ('N', 'AETNA HEALTH & LIFE INS CO (STANDARD)	', '44295'),
             ('N', 'AETNA LIFE INS CO	', '43649'),
             ('N', 'AMERICAN BENEFIT LIFE INS CO (PREFERRED)	', '42437'),
             ('N', 'AMERICAN BENEFIT LIFE INS CO (STANDARD)	', '42441'),
             ('N', 'AMERICAN CONTINENTAL INS CO (PREFERRED)	', '43202'),
             ('N', 'AMERICAN CONTINENTAL INS CO (STANDARD)	', '43204'),
             ('N', 'AMERICAN HOME LIFE INS CO (PREFERRED)	', '53635'),
             ('N', 'AMERICAN HOME LIFE INS CO (STANDARD)	', '53564'),
             ('N', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO	', '44900'),
             ('N', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO	', '45771'),
             ('N', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO (TOBACCO)	', '44904'),
             ('N', 'AMERICO FINANCIAL LIFE & ANNUITY INS CO (TOBACCO)	', '46476'),
             ('N', 'ASSURED LIFE ASSN	', '43763'),
             ('N', 'ASSURED LIFE ASSN (TOBACCO)	', '43764'),
             ('N', 'ATLANTIC COAST LIFE INS CO	', '45733'),
             ('N', 'ATLANTIC COAST LIFE INS CO (TOBACCO)	', '45737'),
             ('N', 'BANKERS FIDELITY LIFE INS CO (PREFERRED)	', '44354'),
             ('N', 'BANKERS FIDELITY LIFE INS CO (STANDARD)	', '44353'),
             ('N', 'BANKERS RESERVE LIFE INS CO OF WISCONSIN	', '53742'),
             ('N', 'BANKERS RESERVE LIFE INS CO OF WISCONSIN (TOBACCO)	', '53769'),
             ('N', 'BLUECROSS BLUESHIELD OF TENNESSEE	', '44483'),
             ('N', 'BLUECROSS BLUESHIELD OF TENNESSEE (TOBACCO)	', '44484'),
             ('N', 'CAPITOL LIFE INS CO (PREFERRED)	', '46269'),
             ('N', 'CAPITOL LIFE INS CO (STANDARD)	', '46273'),
             ('N', 'CENTRAL STATES HEALTH & LIFE OF OMAHA (PREFERRED)	', '45459'),
             ('N', 'CENTRAL STATES HEALTH & LIFE OF OMAHA (STANDARD)	', '45332'),
             ('N', 'CIGNA HEALTH & LIFE INS CO (PREFERRED)	', '44647'),
             ('N', 'CIGNA HEALTH & LIFE INS CO (STANDARD)	', '44642'),
             ('N', 'CIGNA NATIONAL HEALTH INS CO (PREFERRED)	', '46056'),
             ('N', 'CIGNA NATIONAL HEALTH INS CO (STANDARD II)	', '42109'),
             ('N', 'CIGNA NATIONAL HEALTH INS CO (STANDARD III)	', '42113'),
             ('N', 'CIGNA NATIONAL HEALTH INS CO (STANDARD)	', '42105'),
             ('N', 'COLONIAL PENN LIFE INS CO (PREFERRED)	', '44180'),
             ('N', 'COLONIAL PENN LIFE INS CO (STANDARD)	', '43746'),
             ('N', 'COLONIAL PENN LIFE INS CO (SUBSTANDARD)	', '44133'),
             ('N', 'COMPBENEFITS INS CO (PREFERRED)	', '46399'),
             ('N', 'COMPBENEFITS INS CO (STANDARD)	', '46404'),
             ('N', 'CONTINENTAL LIFE INS OF BRENTWOOD (PREFERRED)	', '43655'),
             ('N', 'CONTINENTAL LIFE INS OF BRENTWOOD (STANDARD)	', '43653'),
             ('N', 'ELIPS LIFE INS CO (PREFERRED)	', '42248'),
             ('N', 'ELIPS LIFE INS CO (STANDARD)	', '42253'),
             ('N', 'EPIC LIFE INS CO	', '44627'),
             ('N', 'ERIE FAMILY LIFE INS CO	', '46597'),
             ('N', 'ERIE FAMILY LIFE INS CO (TOBACCO)	', '46461'),
             ('N', 'FEDERAL LIFE INS CO	', '46564'),
             ('N', 'FEDERAL LIFE INS CO (TOBACCO)	', '46444'),
             ('N', 'FIRST HEALTH LIFE & HEALTH INS CO (PREFERRED)	', '44990'),
             ('N', 'FIRST HEALTH LIFE & HEALTH INS CO (STANDARD)	', '44995'),
             ('N', 'GLOBE LIFE & ACCIDENT INS CO	', '44370'),
             ('N', 'GLOBE LIFE & ACCIDENT INS CO	', '46050'),
             ('N', 'GLOBE LIFE & ACCIDENT INS CO (PREFERRED)	', '46045'),
             ('N', 'GREAT SOUTHERN LIFE INS CO	', '45742'),
             ('N', 'GREAT SOUTHERN LIFE INS CO (DIRECT TOBACCO)	', '46155'),
             ('N', 'GREAT SOUTHERN LIFE INS CO (DIRECT)	', '46291'),
             ('N', 'GREAT SOUTHERN LIFE INS CO (TOBACCO)	', '45640'),
             ('N', 'GUARANTEE TRUST LIFE INS CO (PREFERRED)	', '43798'),
             ('N', 'GUARANTEE TRUST LIFE INS CO (STANDARD)	', '43801'),
             ('N', 'HUMANA INS CO (HEALTHY LIVING PREFERRED)	', '45286'),
             ('N', 'HUMANA INS CO (HEALTHY LIVING STANDARD)	', '45281'),
             ('N', 'HUMANA INS CO (PREFERRED)	', '43564'),
             ('N', 'HUMANA INS CO (STANDARD)	', '43563'),
             ('N', 'HUMANADENTAL INS CO (PREFERRED)	', '44449'),
             ('N', 'HUMANADENTAL INS CO (STANDARD)	', '44443'),
             ('N', 'INDEPENDENCE AMERICAN INS CO	', '42029'),
             ('N', 'INDEPENDENCE AMERICAN INS CO (TOBACCO)	', '46681'),
             ('N', 'LUMICO LIFE INS CO (PREFERRED)	', '45707'),
             ('N', 'LUMICO LIFE INS CO (STANDARD)	', '45606'),
             ('N', 'MANHATTAN LIFE INS CO (PREFERRED)	', '43873'),
             ('N', 'MANHATTAN LIFE INS CO (STANDARD)	', '44383'),
             ('N', 'MANHATTANLIFE INS & ANNUITY CO (PREFERRED)	', '42021'),
             ('N', 'MANHATTANLIFE INS & ANNUITY CO (STANDARD)	', '42025'),
             ('N', 'MEDICO CORP LIFE INS CO	', '44253'),
             ('N', 'MEDICO CORP LIFE INS CO (PREFERRED)	', '44161'),
             ('N', 'MEDICO INS CO (PREFERRED)	', '42183'),
             ('N', 'MEDICO INS CO (PREFERRED)	', '43796'),
             ('N', 'MEDICO INS CO (STANDARD I)	', '42069'),
             ('N', 'MEDICO INS CO (STANDARD II)	', '42075'),
             ('N', 'MEDICO INS CO (STANDARD)	', '43794'),
             ('N', 'NASSAU LIFE INS CO OF KANSAS (PREFERRED)	', '46361'),
             ('N', 'NASSAU LIFE INS CO OF KANSAS (STANDARD)	', '46365'),
             ('N', 'NATIONAL GUARDIAN LIFE INS CO	', '45307'),
             ('N', 'NATIONAL GUARDIAN LIFE INS CO (TOBACCO)	', '45311'),
             ('N', 'NATIONAL HEALTH INS CO (PREFERRED II)	', '42635'),
             ('N', 'NATIONAL HEALTH INS CO (PREFERRED)	', '42622'),
             ('N', 'NATIONAL HEALTH INS CO (PREFERRED)	', '45931'),
             ('N', 'NATIONAL HEALTH INS CO (STANDARD)	', '42627'),
             ('N', 'NATIONAL HEALTH INS CO (STANDARD)	', '45793'),
             ('N', 'NEW ERA LIFE INS CO	', '43831'),
             ('N', 'NEW ERA LIFE INS CO (TOBACCO)	', '43832'),
             ('N', 'NEW ERA LIFE INS CO OF THE MIDWEST	', '42398'),
             ('N', 'NEW ERA LIFE INS CO OF THE MIDWEST (TOBACCO)	', '42323'),
             ('N', 'OMAHA INS CO	', '44553'),
             ('N', 'OMAHA INS CO (TOBACCO)	', '44555'),
             ('N', 'ORDER OF UNITED COMMERCIAL TRAVELERS	', '45242'),
             ('N', 'ORDER OF UNITED COMMERCIAL TRAVELERS (TOBACCO)	', '45970'),
             ('N', 'OXFORD LIFE INS CO	', '43836'),
             ('N', 'OXFORD LIFE INS CO (TOBACCO)	', '43840'),
             ('N', 'PAN-AMERICAN LIFE INS CO	', '45918'),
             ('N', 'PAN-AMERICAN LIFE INS CO (TOBACCO)	', '45922'),
             ('N', 'PEKIN LIFE INS CO	', '45073'),
             ('N', 'PEKIN LIFE INS CO (TOBACCO)	', '45074'),
             ('N', 'PHILADELPHIA AMERICAN LIFE INS	', '43378'),
             ('N', 'PHILADELPHIA AMERICAN LIFE INS (TOBACCO)	', '43382'),
             ('N', 'PURITAN LIFE INS CO OF AMERICA (PREFERRED)	', '44862'),
             ('N', 'PURITAN LIFE INS CO OF AMERICA (STANDARD)	', '44866'),
             ('N', 'RESERVE NATIONAL INS CO (PREFERRED)	', '43789'),
             ('N', 'RESERVE NATIONAL INS CO (STANDARD)	', '43749'),
             ('N', 'SBLI USA LIFE INS CO (PREFERRED)	', '42271'),
             ('N', 'SBLI USA LIFE INS CO (STANDARD TOBACCO)	', '42279'),
             ('N', 'SBLI USA LIFE INS CO (STANDARD)	', '42275'),
             ('N', 'SHENANDOAH LIFE INS CO	', '44024'),
             ('N', 'SHENANDOAH LIFE INS CO (TOBACCO)	', '44028'),
             ('N', 'SILVERSCRIPT INS CO (PREFERRED)	', '46686'),
             ('N', 'SILVERSCRIPT INS CO (STANDARD)	', '46691'),
             ('N', 'SOUTHERN GUARANTY INS CO	', '46489'),
             ('N', 'SOUTHERN GUARANTY INS CO (TOBACCO)	', '46493'),
             ('N', 'STANDARD LIFE & CASUALTY INS CO	', '44004'),
             ('N', 'STANDARD LIFE & CASUALTY INS CO	', '46218'),
             ('N', 'STANDARD LIFE & CASUALTY INS CO (TOBACCO)	', '44008'),
             ('N', 'STANDARD LIFE & CASUALTY INS CO (TOBACCO)	', '46222'),
             ('N', 'STATE FARM MUTUAL AUTOMOBILE INS CO	', '45828'),
             ('N', 'STATE FARM MUTUAL AUTOMOBILE INS CO (TOBACCO)	', '45831'),
             ('N', 'STATE MUTUAL INS CO (BROKERAGE PREFERRED)	', '45069'),
             ('N', 'STATE MUTUAL INS CO (BROKERAGE STANDARD)	', '44471'),
             ('N', 'STATE MUTUAL INS CO (BRONZE)	', '46714'),
             ('N', 'STATE MUTUAL INS CO (DIRECT PREFERRED)	', '43686'),
             ('N', 'STATE MUTUAL INS CO (DIRECT STANDARD)	', '43684'),
             ('N', 'STATE MUTUAL INS CO (GOLD)	', '42036'),
             ('N', 'STATE MUTUAL INS CO (SILVER)	', '42045'),
             ('N', 'TIER ONE INS CO (PREFERRED)	', '53733'),
             ('N', 'TIER ONE INS CO (STANDARD)	', '53573'),
             ('N', 'TRANSAMERICA LIFE INS CO	', '43990'),
             ('N', 'TRANSAMERICA LIFE INS CO (TOBACCO)	', '44000'),
             ('N', 'TRH HEALTH INS CO	', '42478'),
             ('N', 'TRH HEALTH INS CO (TOBACCO)	', '42482'),
             ('N', 'UNIFIED LIFE INS CO (PREFERRED)	', '45023'),
             ('N', 'UNIFIED LIFE INS CO (STANDARD)	', '45028'),
             ('N', 'UNION SECURITY INS CO (PREFERRED)	', '45697'),
             ('N', 'UNION SECURITY INS CO (STANDARD)	', '45701'),
             ('N', 'UNITED AMERICAN INS CO (PREFERRED)	', '43374'),
             ('N', 'UNITED AMERICAN INS CO (STANDARD)	', '43447'),
             ('N', 'UNITED INSURANCE COMPANY OF AMERICA (PREFERRED)	', '42061'),
             ('N', 'UNITED INSURANCE COMPANY OF AMERICA (STANDARD)	', '42067'),
             ('N', 'UNITED NATIONAL LIFE INS CO OF AMERICA (PREFERRED)	', '43560'),
             ('N', 'UNITED NATIONAL LIFE INS CO OF AMERICA (STANDARD)	', '43561'),
             ('N', 'UNITED OF OMAHA	', '43470'),
             ('N', 'UNITED OF OMAHA (TOBACCO)	', '43477'),
             ('N', 'UNITED STATES FIRE INS CO (PREFERRED)	', '46331'),
             ('N', 'UNITED STATES FIRE INS CO (STANDARD)	', '46200'),
             ('N', 'UNITED WORLD LIFE INS CO	', '43389'),
             ('N', 'UNITED WORLD LIFE INS CO (TOBACCO)	', '43318'),
             ('N', 'UNITEDHEALTHCARE	', '44676'),
             ('N', 'UNITEDHEALTHCARE (DISCOUNT)	', '44668'),
             ('N', 'UNITEDHEALTHCARE (LEVEL 1)	', '44598'),
             ('N', 'UNITEDHEALTHCARE (LEVEL 2)	', '44512'),
             ('N', 'UNITEDHEALTHCARE (LEVEL 2)	', '44590'),
             ('N', 'UNITEDHEALTHCARE (SELECT DISCOUNT)	', '46185'),
             ('N', 'UNITEDHEALTHCARE (SELECT LEVEL 1)	', '46037'),
             ('N', 'UNITEDHEALTHCARE (SELECT LEVEL 2)	', '46171'),
             ('N', 'UNITEDHEALTHCARE (SELECT LEVEL 2)	', '46189'),
             ('N', 'UNITEDHEALTHCARE (SELECT TOBACCO DISCOUNT)	', '46191'),
             ('N', 'UNITEDHEALTHCARE (SELECT TOBACCO LEVEL 1)	', '46039'),
             ('N', 'UNITEDHEALTHCARE (SELECT TOBACCO LEVEL 2)	', '46175'),
             ('N', 'UNITEDHEALTHCARE (SELECT TOBACCO LEVEL 2)	', '46193'),
             ('N', 'UNITEDHEALTHCARE (SELECT TOBACCO)	', '46173'),
             ('N', 'UNITEDHEALTHCARE (SELECT)	', '46169'),
             ('N', 'UNITEDHEALTHCARE (TOBACCO DISCOUNT)	', '44520'),
             ('N', 'UNITEDHEALTHCARE (TOBACCO LEVEL 1)	', '44968'),
             ('N', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '44976'),
             ('N', 'UNITEDHEALTHCARE (TOBACCO LEVEL 2)	', '45117'),
             ('N', 'UNITEDHEALTHCARE (TOBACCO)	', '45109'),
             ('N', 'USAA LIFE INSURANCE COMPANY	', '44233'),
             ('N', 'USAA LIFE INSURANCE COMPANY (TOBACCO)	', '44234'),
             ('N', 'WASHINGTON NATIONAL INS CO (PREFERRED)	', '53676'),
             ('N', 'WASHINGTON NATIONAL INS CO (STANDARD)	', '53477'),
             ('N', 'WASHINGTON NATIONAL INS CO (SUBSTANDARD)	', '53520'),
             ('N', 'WESTERN UNITED LIFE ASR CO (PREFERRED)	', '44735'),
             ('N', 'WESTERN UNITED LIFE ASR CO (STANDARD)	', '44731'),
             ('A', 'Medicare Supplement	', '10001'),
             ('B', 'Medicare Supplement	', '10002'),
             ('C', 'Medicare Supplement	', '10003'),
             ('D', 'Medicare Supplement	', '10004'),
             ('F', 'Medicare Supplement	', '10005'),
             ('FH', 'Medicare Supplement	', '10006'),
             ('G', 'Medicare Supplement	', '10007'),
             ('GH', 'Medicare Supplement	', '10008'),
             ('K', 'Medicare Supplement	', '10009'),
             ('L', 'Medicare Supplement	', '10010'),
             ('M', 'Medicare Supplement	', '10011'),
             ('N', 'Medicare Supplement	', '10012'),
             ('Not Specified', 'Medicare Supplement	', '10013')) x(plan_type, plan_name, medicare_plan_id);



DROP TABLE IF EXISTS _milliman_pt_pdp_recommendations;

CREATE TEMP TABLE _milliman_pt_pdp_recommendations AS

select distinct expectedpremium,
                bidid,
                memberid,
                planname
from raw.milliman_plan_compare_recommendations rpc
         join raw.plan_compare_covenant_care_duals rpcc on rpc.memberid::bigint = rpcc.patient_id
where producttypeid = '2'
  and rpc.memberid != '';


-- Pt recommended MA values

DROP TABLE IF EXISTS _milliman_pt_ma_recommendations;

CREATE TEMP TABLE _milliman_pt_ma_recommendations AS

select distinct expectedpremium as            ma_expectedpremium,
                bidid,
                memberid,
                planname,
                partbbuydown::int / 12::float ma_monthlypartbbuydown,
                partbbuydown                  ma_partbbuydown,
                -- estimatedmedoopc              ma_estimatedmedoopc,
                0                             ma_estimatedmedoopc,
                estimatedrxoopc               ma_estimatedrxoopc
from raw.milliman_plan_compare_recommendations rpc
         join raw.plan_compare_covenant_care_duals rpcc on rpc.memberid::bigint = rpcc.patient_id
where producttypeid = '1'
  and rpc.memberid != '';

-- Pt recommended med supp values

DROP TABLE IF EXISTS _milliman_pt_med_supp_recommendations;

CREATE TEMP TABLE _milliman_pt_med_supp_recommendations AS

select distinct memberid,
                medicareplanid,
                planname           medsupp_planname,
                plantype           medsupp_plantype,
                -- estimatedmedoopc   medsupp_estimatedmedoopc,
                0                  medsupp_estimatedmedoopc,
                -- estimatedtotaloopc medsupp_estimatedtotaloopc,
                estimatedrxoopc    medsupp_estimatedtotaloopc,
                expectedpremium as medsupp_expectedpremium

from raw.milliman_plan_compare_recommendations rpc
         join raw.plan_compare_covenant_care_duals rpcc on rpc.memberid::bigint = rpcc.patient_id
where producttypeid = '3'
  and rpc.memberid != '';


-- pt recommended Om value
DROP TABLE IF EXISTS _milliman_pt_om_recommendations;

CREATE TEMP TABLE _milliman_pt_om_recommendations AS
select memberid,
       plantype,
-- estimatedmedoopc
       0 as estimatedmedoopc
from raw.milliman_plan_compare_recommendations rpc
         join raw.plan_compare_covenant_care_duals rpcc on rpc.memberid::bigint = rpcc.patient_id
where plantype = 'Original Medicare'
  and rpc.memberid != '';

-- DPC plan id per patient
DROP TABLE IF EXISTS _dpc_patient_plans;

CREATE TEMP TABLE _dpc_patient_plans AS
select distinct CASE
                    WHEN is_part_d AND part_d_contract_id != 'N'
                        THEN CONCAT_WS('_', part_d_contract_id, part_d_pbp_id, segment_id)
                    WHEN is_part_c AND part_c_contract_id != 'N' THEN CONCAT_WS('_', part_c_contract_id, part_c_pbp_id)
                    END plan_id,
                rpcc.patient_id
from prd.dpc_eligibility dpc
         join raw.milliman_plan_compare_recommendations mr on mr.memberid::int = dpc.patient_id
         join raw.plan_compare_covenant_care_duals rpcc on mr.memberid::bigint = rpcc.patient_id
where bom = '2023-06-01'
  and mr.memberid != '';


-- Logic Calculations
DROP TABLE IF EXISTS _milliman_logic_calculations_step_1;
CREATE TEMP TABLE _milliman_logic_calculations_step_1 AS

select mr.id,
       dual_status_code                                                   as dual_level,
       dual_type,
       cost_share_code                                                    as lis_level,
       case when cost_share_code is null then 'Unknown' else lis_type end as lis_type,

       case
           when producttypeid = '3' then 'N'
           when producttypeid = '2' then 'Y'
           when producttypeid = '1' and cms.rx_coverage = 1 then 'Y'
           when producttypeid = '1' and cms.rx_coverage = 2 then 'N'
           else 'N' end                                                   as rx_coverage,
       case
           --    when producttypeid = '3' then (estimatedtotaloopc::float - estimatedmedoopc::float)
           when producttypeid = '3' then 0::float
           else mr.expectedpremium::float
           end                                                            as expectedpremium,
       round((case
           --   when producttypeid = '3' and (estimatedtotaloopc::float - estimatedmedoopc::float) = 0 then
                  when producttypeid = '3' then
                      amp.med_supp_monthly_premium::float
           --   when producttypeid = '3' then (estimatedtotaloopc::float - estimatedmedoopc::float) / 12
                  when producttypeid = '3' and estimatedrxoopc != 'Not Applicable' then (estimatedrxoopc::float) / 12
                  when producttypeid = '2' or producttypeid = '1' then mr.expectedpremium ::float / 12
                  else '0.00'::float end)::numeric,
             2)                                                              monthlypremium,

       partbbuydown::float / 12                                              monthlypartbbuydown,
       case when dpc.part_c_contract_id = 'N' then 'Y' else 'N' end
                                                                          as om_y_n,

       case
           when producttypeid = '1' and plantype = 'Original Medicare' then 0 -- estimatedmedoopc
           else null end                                                  as current_om_oop_medical,

       case
           when substring(dpp.plan_id, 1, 1) = 'S' then dpp.plan_id
           else null end                                                  as current_pdp,
       m_pdp.planname                                                        current_pdp_name,
       round((m_pdp.expectedpremium ::float / 12)::decimal, 2)               current_pdp_premiums,
       m_pdp.expectedpremium::float                                          current_pdp_premium_totals,
       case
           when substring(dpp.plan_id, 1, 1) in ('H', 'R') then dpp.plan_id
           else null end                                                  as current_ma,
       m_ma.planname                                                      as current_ma_plan_name,

       m_ma.ma_expectedpremium::float / 12                                   current_ma_premium,
       m_ma.ma_monthlypartbbuydown                                           current_ma_monthlypartbbuydown,
       round((m_ma.ma_expectedpremium::float / 12 - m_ma.ma_monthlypartbbuydown) ::decimal,
             2)                                                              current_ma_premiumafterbuydown,
       m_ma.ma_expectedpremium                                               current_ma_premiumtotals,
       m_ma.ma_partbbuydown                                                  current_ma_partbbuydown,
       m_ma.ma_estimatedmedoopc                                              current_ma_medicaltotals,
       m_ma.ma_estimatedrxoopc                                               current_ma_rxtotals,
       (m_ma.ma_expectedpremium ::int + m_ma.ma_estimatedmedoopc::int + m_ma.ma_estimatedrxoopc::int) -
       m_ma.ma_partbbuydown::int                                             current_ma_annualtotals,
       m_medsupp.medsupp_plantype                                            current_ms_plantype,
       m_medsupp.medsupp_planname                                            current_ms_planname,
       m_medsupp.medicareplanid                                              current_ms_medicareplanid,
       round((case
                  when (m_medsupp.medsupp_estimatedtotaloopc::float - m_medsupp.medsupp_estimatedmedoopc ::float) = 0
                      then
                      amp_current.med_supp_monthly_premium::float
                  when m_medsupp.medsupp_estimatedtotaloopc::float - m_medsupp.medsupp_estimatedmedoopc ::float > 0
                      then
                          (m_medsupp.medsupp_estimatedtotaloopc::float - m_medsupp.medsupp_estimatedmedoopc ::float) /
                          12

                  else '0.00'::float
           end)::decimal,
             2)                                                              current_ms_premium,
       round((case
                  when (m_medsupp.medsupp_estimatedtotaloopc::float - m_medsupp.medsupp_estimatedmedoopc ::float) = 0
                      then
                      amp_current.med_supp_monthly_premium::float * 12
                  when m_medsupp.medsupp_estimatedtotaloopc::float - m_medsupp.medsupp_estimatedmedoopc ::float > 0
                      then
                      (m_medsupp.medsupp_estimatedtotaloopc::float - m_medsupp.medsupp_estimatedmedoopc ::float)

                  else '0.00'::float
           end)::decimal, 2)                                                 current_ms_premiumtotals


from raw.milliman_plan_compare_recommendations mr
         join raw.plan_compare_covenant_care_duals rpcc on mr.memberid::bigint = rpcc.patient_id
         left join prd.dpc_eligibility dpc
                   on dpc.patient_id = mr.memberid::bigint and bom = '2023-06-01'
         left join _dual_mapping dm on dpc.dual_status_code = dm.dual_level
         left join _lis_mapping lm on dpc.cost_share_code = lm.lis_level
         left join _avg_med_supp_premiums_by_plan amp on amp.med_supp_plan_type = mr.plantype
         left join ref.cms_bid_rx_coverage cms on cms.bid_id = mr.bidid
         left join _dpc_patient_plans dpp on dpc.patient_id = dpp.patient_id
         left join _milliman_pt_pdp_recommendations m_pdp
                   on m_pdp.memberid::int = dpp.patient_id and m_pdp.bidid = substring(dpp.plan_id, 1, 11)
         left join _milliman_pt_ma_recommendations m_ma
                   on m_ma.memberid::int = dpp.patient_id and m_ma.bidid = substring(dpp.plan_id, 1, 11)

         left join ref.plan_compare_patient_current_med_supp_plan_data pc_med_supp
                   on pc_med_supp.patient_id = mr.memberid::int and
                      pc_med_supp.current_medsupp_medicare_planid::int = mr.medicareplanid::int
         left join _milliman_pt_med_supp_recommendations m_medsupp
                   on m_medsupp.memberid::int = pc_med_supp.patient_id and
                      m_medsupp.medicareplanid::int = pc_med_supp.current_medsupp_medicare_planid::int
         left join _avg_med_supp_premiums_by_plan amp_current
                   on amp_current.med_supp_plan_type = pc_med_supp.current_medsupp_plan_type
where mr.memberid != '';

-- select  * from raw.milliman_plan_compare_recommendations mr
--     join raw.plan_compare_covenant_care_duals rpcc on mr.memberid::bigint = rpcc.patient_id
--  where mr.memberid!='' and mr.estimatedrxoopc='Not Applicable';
--
--

-- Second level Calculations/Mappings based on Logic Calcs
DROP TABLE IF EXISTS _milliman_logic_calculations_coverage_combo;
CREATE TEMP TABLE _milliman_logic_calculations_coverage_combo AS

select m1.id,
       case
           when m1.om_y_n = 'Y' and m1.current_pdp is null and m1.current_ms_plantype is null then 'om'
           when m1.om_y_n = 'Y' and m1.current_pdp is not null and m1.current_ms_plantype is null then 'om_pdp'
           when m1.om_y_n = 'Y' and m1.current_pdp is not null and m1.current_ms_plantype is not null
               then 'om_pdp_med_supp'
           when m1.om_y_n = 'N' and m1.current_ma is not null then 'ma'
           end as patient_coverage_combo_code,
       case
           when m1.om_y_n = 'Y' and m1.current_pdp is null and m1.current_ms_plantype is null then 'OM Only'
           when m1.om_y_n = 'Y' and m1.current_pdp is not null and m1.current_ms_plantype is null then 'OM + PDP'
           when m1.om_y_n = 'Y' and m1.current_pdp is not null and m1.current_ms_plantype is not null
               then 'OM + Med Supp + PDP'
           when m1.om_y_n = 'N' and m1.current_ma is not null then 'Medicare Advantage'
           end as patient_coverage_combo
from _milliman_logic_calculations_step_1 m1
         join raw.milliman_plan_compare_recommendations mr on mr.id = m1.id;

---more calculations
DROP TABLE IF EXISTS _milliman_logic_calculations_step_2;
CREATE TEMP TABLE _milliman_logic_calculations_step_2 AS

select m1.id,
       round((m1.monthlypremium - m1.monthlypartbbuydown)::decimal, 2) monthly_premiumafterbuydown,
       case
           when dual_level in ('01', '02', '04') then '0.00'::decimal
           when dual_level not in ('01', '02', '04') and
                mcc.patient_coverage_combo_code in ('om', 'om_pdp') then om.estimatedmedoopc::decimal
           when dual_level not in ('01', '02', '04') and
                mcc.patient_coverage_combo_code in ('ma') then 0::decimal --mr.estimatedmedoopc::decimal
           end                                                         estimated_med_oop_withmedical,

       round((case
                  when mr.estimatedrxoopc = 'Not Applicable' then '0.00'
                  when mr.estimatedrxoopc::int > 0 then mr.estimatedrxoopc::decimal
                  else '0.00' end)::decimal,
             2) as                                                     estimated_rx_oop_totals
from _milliman_logic_calculations_step_1 m1
         join raw.milliman_plan_compare_recommendations mr on mr.id = m1.id
         join _milliman_logic_calculations_coverage_combo mcc on mcc.id = mr.id
         join _milliman_pt_om_recommendations om on om.memberid::int = mr.memberid::int;


-- final calculations

drop table if exists staging.milliman_plan_compare_step_4a_outcomes;

select m1.id                                                                        milliman_record_id,
       mr.memberid,
       mr.contactid,
       mr.firstname,
       mr.lastname,
       mr.dob,
       mr.address1,
       mr.address2,
       mr.city,
       mr.state,
       mr.zip,
       m1.dual_level,
       m1.dual_type,
       m1.lis_level,
       m1.lis_type,
       mr.plantype,
       mr.planname,
       m1.rx_coverage,
       mr.producttypeid,
       mr.medicareplanid,
       mr.bidid,
       m1.expectedpremium,
       m1.monthlypremium,
       m1.monthlypartbbuydown,
       m2.monthly_premiumafterbuydown,
       --    mr.estimatedmedoopc,
       0                  as                                                        estimatedmedoopc,
       m2.estimated_med_oop_withmedical,
       mr.estimatedrxoopc,
       m2.estimated_rx_oop_totals,
       --    mr.estimatedtotaloopc,
       mr.estimatedrxoopc as                                                        estimatedtotaloopc,
       ((m2.monthly_premiumafterbuydown * 12) + m2.estimated_med_oop_withmedical +
        m2.estimated_rx_oop_totals)::decimal                                        estimated_total_oop_all_in,
       mr.partbbuydown,
       ((m2.monthly_premiumafterbuydown * 12) + m2.estimated_med_oop_withmedical +
        m2.estimated_rx_oop_totals)::decimal - mr.partbbuydown::decimal             total_oop_after_buydown,
       round((mr.partbbuydown::int + mr.supplementalbenefitvalue::int)::decimal, 2) overall_value,

       case
           when mr.estimatedrxoopc = 'Not Applicable' then
               round((mr.partbbuydown::int + mr.supplementalbenefitvalue::int -
                   --   mr.estimatedtotaloopc::int)::decimal, 2)                              true_net_impact,
                      0::int)::decimal, 2)
           else
               round((mr.partbbuydown::int + mr.supplementalbenefitvalue::int -
                   --   mr.estimatedtotaloopc::int)::decimal, 2)                              true_net_impact,
                      mr.estimatedrxoopc::int)::decimal, 2) end
                                                                                    true_net_impact,
       mcc.patient_coverage_combo_code,
       mcc.patient_coverage_combo,
       m1.om_y_n,
       m1.current_om_oop_medical,
       m1.current_pdp,
       m1.current_pdp_name,
       m1.current_pdp_premiums,
       m1.current_pdp_premium_totals,
       m1.current_ma,
       m1.current_ma_plan_name,
       m1.current_ma_premium,
       m1.current_ma_monthlypartbbuydown,
       m1.current_ma_premiumafterbuydown,
       m1.current_ma_premiumtotals,
       m1.current_ma_partbbuydown,
       m1.current_ma_medicaltotals,
       m1.current_ma_rxtotals,
       m1.current_ma_annualtotals,
       m1.current_ms_plantype,
       m1.current_ms_planname,
       m1.current_ms_medicareplanid,
       m1.current_ms_premium,
       m1.current_ms_premiumtotals,
       mr.preferredstatusretail,
       mr.preferredstatusmail,
       mr.pharmacyretail,
       mr.pharmacymail,
       mr.preventive_limit,
       mr.preventive_limit_period,
       mr.preventive_dental_prophylaxis_cleaning_visit_limit,
       mr.preventive_dental_prophylaxis_cleaning_visit_limit_period,
       mr.comprehensive_limit,
       mr.comprehensive_limit_period,
       mr.vision_exams_cost_sharing,
       mr.vision_exams_limit,
       mr.vision_exams_limit_period,
       mr.vision_combined_limit,
       mr.vision_combined_limit_period,
       mr.hearing_routine_hearing_test_cost_sharing,
       mr.hearing_aids_limit,
       mr.hearing_aids_limit_period,
       mr.hearing_aids_benefit_limit,
       mr.hearing_aids_benefit_limit_period,
       mr.non_er_transport_type,
       mr.non_er_transport_one_way_trip_limit,
       mr.non_er_transport_one_way_trip_limit_period,
       mr.chiropractic_routine_coverage,
       mr.chiropractic_routine_coverage_visit_limit,
       mr.chiropractic_routine_coverage_limit_period,
       mr.acupuncture_cost_sharing,
       mr.acupuncture_visit_limit,
       mr.acupuncture_limit_period,
       mr.over_the_counter_drug_card,
       mr.over_the_counter_drug_card_period,
       mr.meal_benefit,
       mr.worldwide_er_cost_sharing,
       mr.worldwide_er_limit,
       mr.fitness_benefit,
       mr.type_of_fitness_benefit,
       mr.bathroom_safety_devices,
       mr.in_home_safety_assessment,
       mr.personal_emergency_response_system_pers,
       mr.wigs_for_hair_loss_related_to_chemotherapy,
       mr.support_for_caregivers_of_enrollees,
       mr.combined_limit_flex_benefit_package_1_limit,
       mr.combined_limit_flex_benefit_package_1_limit_period
into staging.milliman_plan_compare_step_4a_outcomes
from _milliman_logic_calculations_step_1 m1
         join raw.milliman_plan_compare_recommendations mr on mr.id = m1.id
         join _milliman_logic_calculations_coverage_combo mcc on mcc.id = mr.id
         join _milliman_logic_calculations_step_2 m2 on m2.id = m1.id
         join _milliman_pt_om_recommendations om on om.memberid::int = mr.memberid::int;


select * from staging.milliman_plan_compare_step_4a_outcomes;
